fix: Full shellcheck and bash strict mode
Went through every script and put strict mode in place as well as fixed
many ShellCheck lint recommendations.

diff --git a/bin/cheat b/bin/cheat
--- a/bin/cheat
+++ b/bin/cheat
@@ -1,6 +1,25 @@
 #!/usr/bin/env bash
 # Author: Alexander Epstein https://github.com/alexanderepstein
 
+# Bash strict mode
+# shellcheck disable=SC2154
+([[ -n ${ZSH_EVAL_CONTEXT} && ${ZSH_EVAL_CONTEXT} =~ :file$ ]] ||
+ [[ -n ${BASH_VERSION} ]] && (return 0 2>/dev/null)) && SOURCED=true || SOURCED=false
+if ! ${SOURCED}; then
+  set -o errexit # same as set -e
+  set -o nounset # same as set -u
+  set -o errtrace # same as set -E
+  set -o pipefail
+  set -o posix
+  #set -o xtrace # same as set -x, turn on for debugging
+
+  shopt -s extdebug
+  IFS=$(printf '\n\t')
+fi
+# END Bash scrict mode
+
+shopt -s inherit_errexit
+
 currentVersion="1.22.0"
 configuredClient=""
 ## rest of these variables are search flags
@@ -29,11 +48,15 @@ getConfiguredClient()
 ## Allows to call the users configured client without if statements everywhere
 httpGet()
 {
-  case "$configuredClient" in
+  case "${configuredClient}" in
     curl)  curl -A curl -s "$@" ;;
     wget)  wget -qO- "$@" ;;
     httpie) http -b GET "$@" ;;
     fetch) fetch -q "$@" ;;
+    *)
+       echo "Error: Unknown client"
+       return 1
+      ;;
   esac
 }
 
@@ -51,38 +74,38 @@ update()
   repositoryName="Bash-Snippets" #Name of repostiory to be updated ex. Sandman-Lite
   githubUserName="alexanderepstein" #username that hosts the repostiory ex. alexanderepstein
   nameOfInstallFile="install.sh" # change this if the installer file has a different name be sure to include file extension if there is one
-  latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",'| head -1 | grep -Eo "[0-9.]+" ) #always grabs the tag without the v option
+  latestVersion=$(httpGet https://api.github.com/repos/${githubUserName}/${repositoryName}/tags | grep -Eo '"name":.*?[^\\]",'| head -1 | grep -Eo "[0-9.]+" ) #always grabs the tag without the v option
 
-  if [[ $currentVersion == "" || $repositoryName == "" || $githubUserName == "" || $nameOfInstallFile == "" ]]; then
+  if [[ ${currentVersion} == "" || ${repositoryName} == "" || ${githubUserName} == "" || ${nameOfInstallFile} == "" ]]; then
     echo "Error: update utility has not been configured correctly." >&2
     exit 1
-  elif [[ $latestVersion == "" ]]; then
+  elif [[ ${latestVersion} == "" ]]; then
     echo "Error: no active internet connection" >&2
     exit 1
   else
-    if [[ "$latestVersion" != "$currentVersion" ]]; then
-      echo "Version $latestVersion available"
-      echo -n "Do you wish to update $repositoryName [Y/n]: "
+    if [[ "${latestVersion}" != "${currentVersion}" ]]; then
+      echo "Version ${latestVersion} available"
+      echo -n "Do you wish to update ${repositoryName} [Y/n]: "
       read -r answer
-      if [[ "$answer" == [Yy] ]]; then
+      if [[ "${answer}" == [Yy] ]]; then
         cd ~ || { echo 'Update Failed'; exit 1; }
-        if [[ -d  ~/$repositoryName ]]; then rm -r -f $repositoryName || { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
-        echo -n "Downloading latest version of: $repositoryName."
-        git clone -q "https://github.com/$githubUserName/$repositoryName" && touch .BSnippetsHiddenFile || { echo "Failure!"; exit 1; } &
-        while [ ! -f .BSnippetsHiddenFile ]; do { echo -n "."; sleep 2; };done
+        if [[ -d  ~/${repositoryName} ]]; then rm -r -f "${repositoryName}" || { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
+        echo -n "Downloading latest version of: ${repositoryName}."
+        git clone -q "https://github.com/${githubUserName}/${repositoryName}" && touch .BSnippetsHiddenFile || { echo "Failure!"; exit 1; } &
+        while [[ ! -f .BSnippetsHiddenFile ]]; do { echo -n "."; sleep 2; };done
         rm -f .BSnippetsHiddenFile
         echo "Success!"
-        cd $repositoryName || { echo 'Update Failed'; exit 1; }
-        git checkout "v$latestVersion" 2> /dev/null || git checkout "$latestVersion" 2> /dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
+        cd "${repositoryName}" || { echo 'Update Failed'; exit 1; }
+        git checkout "v${latestVersion}" 2> /dev/null || git checkout "${latestVersion}" 2> /dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
         chmod a+x install.sh #this might be necessary in your case but wasnt in mine.
-        ./$nameOfInstallFile "update" || exit 1
+        ./"${nameOfInstallFile}" "update" || exit 1
         cd ..
-        rm -r -f $repositoryName || { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"; exit 1; }
+        rm -r -f "${repositoryName}" || { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/${repositoryName} delete this directory with sudo"; exit 1; }
       else
         exit 1
       fi
     else
-      echo "$repositoryName is already the latest version"
+      echo "${repositoryName} is already the latest version"
     fi
   fi
 }
@@ -117,7 +140,7 @@ EOF
 getCheatSheet()
 {
   if [[ $# == 1 ]]; then
-    if [[ $search == "1" ]]; then
+    if [[ ${search} == "1" ]]; then
       link=cheat.sh/~$1
     else
       link=cheat.sh/$1
@@ -127,16 +150,16 @@ getCheatSheet()
   fi
 
   if [[ $# == 2 ]]; then
-    if [[ $search == "1" ]]; then
+    if [[ ${search} == "1" ]]; then
       link+=/~$2 ## add this to end of link where ~ indicates search
     else
       link+=/$2 ## add this to end of link
     fi
   fi
 
-  if [[ $insensitive != "" || $recursive != "" || $boundry != "" ]]; then link+=/$boundry$insensitive$recursive; fi ## add this to the end of the link as flags
+  if [[ ${insensitive} != "" || ${recursive} != "" || ${boundry} != "" ]]; then link+=/${boundry}${insensitive}${recursive}; fi ## add this to the end of the link as flags
 
-  httpGet $link
+  httpGet "${link}"
 }
 
 
@@ -152,9 +175,9 @@ checkSpecialPage()
     temp=":styles"
   fi
   if [[ $2 == "1" ]]; then
-    arg1=$temp
+    arg1=${temp}
   else
-    arg2=$temp
+    arg2=${temp}
   fi
 }
 
@@ -162,14 +185,14 @@ getConfiguredClient || exit 1
 
 
 while getopts "ribuvhis" opt; do
-  case "$opt" in
-    \?) echo "Invalid option: -$OPTARG" >&2
+  case "${opt}" in
+    \?) echo "Invalid option: -${OPTARG}" >&2
         exit 1
         ;;
     h)  usage
         exit 0
         ;;
-    v)  echo "Version $currentVersion"
+    v)  echo "Version ${currentVersion}"
         exit 0
         ;;
     u)
@@ -188,27 +211,31 @@ while getopts "ribuvhis" opt; do
         ;;
     s)  search="1"
         ;;
-    :)  echo "Option -$OPTARG requires an argument." >&2
+    :)  echo "Option -${OPTARG} requires an argument." >&2
         exit 1
         ;;
+    *)
+      echo "Unknown error"
+      exit 1
+      ;;
   esac
 done
 
 ### This functions sets arg 1 and arg 2 to be unqique items after the options
 for arg; do
-  if [[ $arg != "-r" && $arg != "-s" && $arg != "-b" && $arg != "-i" ]]; then
-    if [ -z ${arg1+x} ]; then
-      arg1=$arg
+  if [[ ${arg} != "-r" && ${arg} != "-s" && ${arg} != "-b" && ${arg} != "-i" ]]; then
+    if [[ -z ${arg1+x} ]]; then
+      arg1=${arg}
     fi
-    if [ ! -z ${arg1+x} ]; then
-      arg2=$arg
+    if [[ -n ${arg1+x} ]]; then
+      arg2=${arg}
     fi
   fi
 done
 
 ## check for special pages before moving on
-checkSpecialPage $arg1 1
-checkSpecialPage $arg2 2
+checkSpecialPage "${arg1}" 1
+checkSpecialPage "${arg2}" 2
 
 if [[ $# == 0 ]]; then
   usage
@@ -222,11 +249,11 @@ elif [[ $1 == "help" || $1 == ":help" ]]; then ## shows the help and prevents th
   exit 0
 else
   checkInternet || exit 1
-  if [[ $arg1 != $arg2 ]]; then ## if they equal each other that means there was no arg 2 supplied
-    getCheatSheet $arg1 $arg2
+  if [[ ${arg1} != "${arg2}" ]]; then ## if they equal each other that means there was no arg 2 supplied
+    getCheatSheet "${arg1}" "${arg2}"
     exit 0
   else
-    getCheatSheet $arg1
+    getCheatSheet "${arg1}"
     exit 0
   fi
   exit 0
diff --git a/bin/crypt b/bin/crypt
--- a/bin/crypt
+++ b/bin/crypt
@@ -1,6 +1,23 @@
 #!/usr/bin/env bash
 # Author: Alexander Epstein https://github.com/alexanderepstein
 
+# Bash strict mode
+# shellcheck disable=SC2154
+([[ -n ${ZSH_EVAL_CONTEXT} && ${ZSH_EVAL_CONTEXT} =~ :file$ ]] ||
+ [[ -n ${BASH_VERSION} ]] && (return 0 2>/dev/null)) && SOURCED=true || SOURCED=false
+if ! ${SOURCED}; then
+  set -o errexit # same as set -e
+  set -o nounset # same as set -u
+  set -o errtrace # same as set -E
+  set -o pipefail
+  set -o posix
+  #set -o xtrace # same as set -x, turn on for debugging
+
+  shopt -s extdebug
+  IFS=$(printf '\n\t')
+fi
+# END Bash scrict mode
+
 currentVersion="1.22.0"
 state=""
 configuredClient=""
@@ -40,11 +57,12 @@ getConfiguredClient()
 ## Allows to call the users configured client without if statements everywhere
 httpGet()
 {
-  case "$configuredClient" in
+  case "${configuredClient}" in
     curl)  curl -A curl -s "$@" ;;
     wget)  wget -qO- "$@" ;;
     httpie) http -b GET "$@" ;;
     fetch) fetch -q "$@" ;;
+    *) ;;
   esac
 }
 
@@ -52,7 +70,7 @@ httpGet()
 encrypt()
 {
   echo "Encrypting $1..."
-  openssl enc -aes-256-cbc -salt -a -in $1 -out $2 || { echo "File not found"; return 1; }
+  openssl enc -aes-256-cbc -salt -a -in "$1" -out "$2" || { echo "File not found"; return 1; }
   echo "Successfully encrypted"
 }
 
@@ -60,7 +78,7 @@ encrypt()
 decrypt()
 {
   echo "Decrypting $1..."
-  openssl enc -aes-256-cbc -d -a -in $1 -out $2 || { echo "File not found"; return 1; }
+  openssl enc -aes-256-cbc -d -a -in "$1" -out "$2" || { echo "File not found"; return 1; }
   echo "Successfully decrypted"
 }
 
@@ -72,38 +90,38 @@ update()
   repositoryName="Bash-Snippets" #Name of repostiory to be updated ex. Sandman-Lite
   githubUserName="alexanderepstein" #username that hosts the repostiory ex. alexanderepstein
   nameOfInstallFile="install.sh" # change this if the installer file has a different name be sure to include file extension if there is one
-  latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",'| head -1 | grep -Eo "[0-9.]+" ) #always grabs the tag without the v option
+  latestVersion=$(httpGet https://api.github.com/repos/${githubUserName}/${repositoryName}/tags | grep -Eo '"name":.*?[^\\]",'| head -1 | grep -Eo "[0-9.]+" ) #always grabs the tag without the v option
 
-  if [[ $currentVersion == "" || $repositoryName == "" || $githubUserName == "" || $nameOfInstallFile == "" ]]; then
+  if [[ ${currentVersion} == "" || ${repositoryName} == "" || ${githubUserName} == "" || ${nameOfInstallFile} == "" ]]; then
     echo "Error: update utility has not been configured correctly." >&2
     exit 1
-  elif [[ $latestVersion == "" ]]; then
+  elif [[ ${latestVersion} == "" ]]; then
     echo "Error: no active internet connection" >&2
     exit 1
   else
-    if [[ "$latestVersion" != "$currentVersion" ]]; then
-      echo "Version $latestVersion available"
-      echo -n "Do you wish to update $repositoryName [Y/n]: "
+    if [[ "${latestVersion}" != "${currentVersion}" ]]; then
+      echo "Version ${latestVersion} available"
+      echo -n "Do you wish to update ${repositoryName} [Y/n]: "
       read -r answer
-      if [[ "$answer" == [Yy] ]]; then
+      if [[ "${answer}" == [Yy] ]]; then
         cd ~ || { echo 'Update Failed'; exit 1; }
-        if [[ -d  ~/$repositoryName ]]; then rm -r -f $repositoryName || { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
-        echo -n "Downloading latest version of: $repositoryName."
-        git clone -q "https://github.com/$githubUserName/$repositoryName" && touch .BSnippetsHiddenFile || { echo "Failure!"; exit 1; } &
-        while [ ! -f .BSnippetsHiddenFile ]; do { echo -n "."; sleep 2; };done
+        if [[ -d  ~/${repositoryName} ]]; then rm -r -f "${repositoryName}" || { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
+        echo -n "Downloading latest version of: ${repositoryName}."
+        git clone -q "https://github.com/${githubUserName}/${repositoryName}" && touch .BSnippetsHiddenFile || { echo "Failure!"; exit 1; } &
+        while [[ ! -f .BSnippetsHiddenFile ]]; do { echo -n "."; sleep 2; };done
         rm -f .BSnippetsHiddenFile
         echo "Success!"
-        cd $repositoryName || { echo 'Update Failed'; exit 1; }
-        git checkout "v$latestVersion" 2> /dev/null || git checkout "$latestVersion" 2> /dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
+        cd "${repositoryName}" || { echo 'Update Failed'; exit 1; }
+        git checkout "v${latestVersion}" 2> /dev/null || git checkout "${latestVersion}" 2> /dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
         chmod a+x install.sh #this might be necessary in your case but wasnt in mine.
-        ./$nameOfInstallFile "update" || exit 1
+        ./"${nameOfInstallFile}" "update" || exit 1
         cd ..
-        rm -r -f $repositoryName || { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"; exit 1; }
+        rm -r -f "${repositoryName}" || { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/${repositoryName} delete this directory with sudo"; exit 1; }
       else
         exit 1
       fi
     else
-      echo "$repositoryName is already the latest version"
+      echo "${repositoryName} is already the latest version"
     fi
   fi
 }
@@ -129,9 +147,9 @@ EOF
 checkOpenSSL || exit 1
 
 while getopts "huve:d:" opt; do ## alows for using options in bash
-  case $opt in
+  case ${opt} in
     e)  ## when trying to encrypt run this
-        if [[ $state != "decrypt" ]]; then
+        if [[ ${state} != "decrypt" ]]; then
           state="encrypt"
         else
           echo "Error: the -d and -e options are mutally exclusive" >&2
@@ -142,11 +160,11 @@ while getopts "huve:d:" opt; do ## alows for using options in bash
           exit 1
         fi
         ;;
-    \?) echo "Invalid option: -$OPTARG" >&2
+    \?) echo "Invalid option: -${OPTARG}" >&2
         exit 1
         ;;
     d)  ## when trying to decrypt run this
-        if [[ $state != "encrypt" ]]; then
+        if [[ ${state} != "encrypt" ]]; then
           state="decrypt"
         else
           echo "Error: the -e and -d options are mutally exclusive" >&2
@@ -165,13 +183,15 @@ while getopts "huve:d:" opt; do ## alows for using options in bash
     h)  usage
         exit 0
         ;;
-    v)  echo "Version $currentVersion"
+    v)  echo "Version ${currentVersion}"
         exit 0
         ;;
     :)  ## will run when no arguments are provided to to e or d options
-        echo "Option -$OPTARG requires an argument." >&2
+        echo "Option -${OPTARG} requires an argument." >&2
         exit 1
         ;;
+    *)
+      ;;
   esac
 done
 
@@ -186,10 +206,10 @@ elif [[ $1 == "update" ]]; then
 elif [[ $1 == "help" ]]; then
   usage
   exit 0
-elif [[ $state == "encrypt" ]]; then
-  encrypt $2 $3 || exit 1
+elif [[ ${state} == "encrypt" ]]; then
+  encrypt "$2" "$3" || exit 1
   exit 0
-elif [[ $state == "decrypt" ]]; then
-  decrypt $2 $3 || exit 1
+elif [[ ${state} == "decrypt" ]]; then
+  decrypt "$2" "$3" || exit 1
   exit 0
 fi
