chore(scripts): Reformatting, spelling

diff --git a/bin/cheat b/bin/cheat
--- a/bin/cheat
+++ b/bin/cheat
@@ -4,10 +4,10 @@
 # Bash strict mode
 # shellcheck disable=SC2154
 ([[ -n ${ZSH_EVAL_CONTEXT} && ${ZSH_EVAL_CONTEXT} =~ :file$ ]] ||
- [[ -n ${BASH_VERSION} ]] && (return 0 2>/dev/null)) && SOURCED=true || SOURCED=false
+  [[ -n ${BASH_VERSION} ]] && (return 0 2>/dev/null)) && SOURCED=true || SOURCED=false
 if ! ${SOURCED}; then
-  set -o errexit # same as set -e
-  set -o nounset # same as set -u
+  set -o errexit  # same as set -e
+  set -o nounset  # same as set -u
   set -o errtrace # same as set -E
   set -o pipefail
   set -o posix
@@ -16,7 +16,7 @@ if ! ${SOURCED}; then
   shopt -s extdebug
   IFS=$(printf '\n\t')
 fi
-# END Bash scrict mode
+# END Bash strict mode
 
 shopt -s inherit_errexit
 
@@ -29,9 +29,8 @@ recursive=""
 boundry=""
 
 ## This function determines which http get tool the system has installed and returns an error if there isnt one
-getConfiguredClient()
-{
-  if  command -v curl &>/dev/null; then
+getConfiguredClient() {
+  if command -v curl &>/dev/null; then
     configuredClient="curl"
   elif command -v wget &>/dev/null; then
     configuredClient="wget"
@@ -46,35 +45,34 @@ getConfiguredClient()
 }
 
 ## Allows to call the users configured client without if statements everywhere
-httpGet()
-{
+httpGet() {
   case "${configuredClient}" in
-    curl)  curl -A curl -s "$@" ;;
-    wget)  wget -qO- "$@" ;;
-    httpie) http -b GET "$@" ;;
-    fetch) fetch -q "$@" ;;
-    *)
-       echo "Error: Unknown client"
-       return 1
-      ;;
+  curl) curl -A curl -s "$@" ;;
+  wget) wget -qO- "$@" ;;
+  httpie) http -b GET "$@" ;;
+  fetch) fetch -q "$@" ;;
+  *)
+    echo "Error: Unknown client"
+    return 1
+    ;;
   esac
 }
 
-
-checkInternet()
-{
-  httpGet github.com > /dev/null 2>&1 || { echo "Error: no active internet connection" >&2; return 1; } # query github with a get request
+checkInternet() {
+  httpGet github.com >/dev/null 2>&1 || {
+    echo "Error: no active internet connection" >&2
+    return 1
+  } # query github with a get request
 }
 
-update()
-{
+update() {
   # Author: Alexander Epstein https://github.com/alexanderepstein
   # Update utility version 2.2.0
   # To test the tool enter in the defualt values that are in the examples for each variable
-  repositoryName="Bash-Snippets" #Name of repostiory to be updated ex. Sandman-Lite
-  githubUserName="alexanderepstein" #username that hosts the repostiory ex. alexanderepstein
-  nameOfInstallFile="install.sh" # change this if the installer file has a different name be sure to include file extension if there is one
-  latestVersion=$(httpGet https://api.github.com/repos/${githubUserName}/${repositoryName}/tags | grep -Eo '"name":.*?[^\\]",'| head -1 | grep -Eo "[0-9.]+" ) #always grabs the tag without the v option
+  repositoryName="Bash-Snippets"                                                                                                                               #Name of repostiory to be updated ex. Sandman-Lite
+  githubUserName="alexanderepstein"                                                                                                                            #username that hosts the repostiory ex. alexanderepstein
+  nameOfInstallFile="install.sh"                                                                                                                               # change this if the installer file has a different name be sure to include file extension if there is one
+  latestVersion=$(httpGet https://api.github.com/repos/${githubUserName}/${repositoryName}/tags | grep -Eo '"name":.*?[^\\]",' | head -1 | grep -Eo "[0-9.]+") #always grabs the tag without the v option
 
   if [[ ${currentVersion} == "" || ${repositoryName} == "" || ${githubUserName} == "" || ${nameOfInstallFile} == "" ]]; then
     echo "Error: update utility has not been configured correctly." >&2
@@ -88,19 +86,37 @@ update()
       echo -n "Do you wish to update ${repositoryName} [Y/n]: "
       read -r answer
       if [[ "${answer}" == [Yy] ]]; then
-        cd ~ || { echo 'Update Failed'; exit 1; }
-        if [[ -d  ~/${repositoryName} ]]; then rm -r -f "${repositoryName}" || { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
+        cd ~ || {
+          echo 'Update Failed'
+          exit 1
+        }
+        if [[ -d ~/${repositoryName} ]]; then rm -r -f "${repositoryName}" || {
+          echo "Permissions Error: try running the update as sudo"
+          exit 1
+        }; fi
         echo -n "Downloading latest version of: ${repositoryName}."
-        git clone -q "https://github.com/${githubUserName}/${repositoryName}" && touch .BSnippetsHiddenFile || { echo "Failure!"; exit 1; } &
-        while [[ ! -f .BSnippetsHiddenFile ]]; do { echo -n "."; sleep 2; };done
+        git clone -q "https://github.com/${githubUserName}/${repositoryName}" && touch .BSnippetsHiddenFile || {
+          echo "Failure!"
+          exit 1
+        } &
+        while [[ ! -f .BSnippetsHiddenFile ]]; do {
+          echo -n "."
+          sleep 2
+        }; done
         rm -f .BSnippetsHiddenFile
         echo "Success!"
-        cd "${repositoryName}" || { echo 'Update Failed'; exit 1; }
-        git checkout "v${latestVersion}" 2> /dev/null || git checkout "${latestVersion}" 2> /dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
+        cd "${repositoryName}" || {
+          echo 'Update Failed'
+          exit 1
+        }
+        git checkout "v${latestVersion}" 2>/dev/null || git checkout "${latestVersion}" 2>/dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
         chmod a+x install.sh #this might be necessary in your case but wasnt in mine.
         ./"${nameOfInstallFile}" "update" || exit 1
         cd ..
-        rm -r -f "${repositoryName}" || { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/${repositoryName} delete this directory with sudo"; exit 1; }
+        rm -r -f "${repositoryName}" || {
+          echo "Permissions Error: update succesfull but cannot delete temp files located at ~/${repositoryName} delete this directory with sudo"
+          exit 1
+        }
       else
         exit 1
       fi
@@ -110,9 +126,8 @@ update()
   fi
 }
 
-usage()
-{
-cat <<EOF
+usage() {
+  cat <<EOF
 Cheat
 Description: Cheatsheets for quick information about multiple programming languages along with terminal commands
 Usage: cheat [flags] [command] or cheat [flags] [programming language] [subject]
@@ -137,8 +152,7 @@ Examples:
 EOF
 }
 
-getCheatSheet()
-{
+getCheatSheet() {
   if [[ $# == 1 ]]; then
     if [[ ${search} == "1" ]]; then
       link=cheat.sh/~$1
@@ -162,10 +176,8 @@ getCheatSheet()
   httpGet "${link}"
 }
 
-
 ### This function just wraps some of the special pages provided by cheat.sh
-checkSpecialPage()
-{
+checkSpecialPage() {
   temp=$1
   if [[ $1 == "list" ]]; then
     temp=":list"
@@ -183,41 +195,48 @@ checkSpecialPage()
 
 getConfiguredClient || exit 1
 
-
 while getopts "ribuvhis" opt; do
   case "${opt}" in
-    \?) echo "Invalid option: -${OPTARG}" >&2
-        exit 1
-        ;;
-    h)  usage
-        exit 0
-        ;;
-    v)  echo "Version ${currentVersion}"
-        exit 0
-        ;;
-    u)
-        checkInternet || exit 1
-        update
-        exit 0
-        ;;
-    i)  insensitive="i"
-        search="1"
-        ;;
-    b)  boundry="b"
-        search="1"
-        ;;
-    r)  recursive="r"
-        search="1"
-        ;;
-    s)  search="1"
-        ;;
-    :)  echo "Option -${OPTARG} requires an argument." >&2
-        exit 1
-        ;;
-    *)
-      echo "Unknown error"
-      exit 1
-      ;;
+  \?)
+    echo "Invalid option: -${OPTARG}" >&2
+    exit 1
+    ;;
+  h)
+    usage
+    exit 0
+    ;;
+  v)
+    echo "Version ${currentVersion}"
+    exit 0
+    ;;
+  u)
+    checkInternet || exit 1
+    update
+    exit 0
+    ;;
+  i)
+    insensitive="i"
+    search="1"
+    ;;
+  b)
+    boundry="b"
+    search="1"
+    ;;
+  r)
+    recursive="r"
+    search="1"
+    ;;
+  s)
+    search="1"
+    ;;
+  :)
+    echo "Option -${OPTARG} requires an argument." >&2
+    exit 1
+    ;;
+  *)
+    echo "Unknown error"
+    exit 1
+    ;;
   esac
 done
 
diff --git a/bin/crypt b/bin/crypt
--- a/bin/crypt
+++ b/bin/crypt
@@ -4,10 +4,10 @@
 # Bash strict mode
 # shellcheck disable=SC2154
 ([[ -n ${ZSH_EVAL_CONTEXT} && ${ZSH_EVAL_CONTEXT} =~ :file$ ]] ||
- [[ -n ${BASH_VERSION} ]] && (return 0 2>/dev/null)) && SOURCED=true || SOURCED=false
+  [[ -n ${BASH_VERSION} ]] && (return 0 2>/dev/null)) && SOURCED=true || SOURCED=false
 if ! ${SOURCED}; then
-  set -o errexit # same as set -e
-  set -o nounset # same as set -u
+  set -o errexit  # same as set -e
+  set -o nounset  # same as set -u
   set -o errtrace # same as set -E
   set -o pipefail
   set -o posix
@@ -16,15 +16,14 @@ if ! ${SOURCED}; then
   shopt -s extdebug
   IFS=$(printf '\n\t')
 fi
-# END Bash scrict mode
+# END Bash strict mode
 
 currentVersion="1.22.0"
 state=""
 configuredClient=""
 
-checkOpenSSL()
-{
-  if  ! command -v openssl &>/dev/null; then
+checkOpenSSL() {
+  if ! command -v openssl &>/dev/null; then
     echo "Error: to use this tool openssl must be installed" >&2
     return 1
   else
@@ -32,15 +31,16 @@ checkOpenSSL()
   fi
 }
 
-checkInternet()
-{
-  httpGet github.com > /dev/null 2>&1 || { echo "Error: no active internet connection" >&2; return 1; } # query github with a get request
+checkInternet() {
+  httpGet github.com >/dev/null 2>&1 || {
+    echo "Error: no active internet connection" >&2
+    return 1
+  } # query github with a get request
 }
 
 ## This function determines which http get tool the system has installed and returns an error if there isnt one
-getConfiguredClient()
-{
-  if  command -v curl &>/dev/null; then
+getConfiguredClient() {
+  if command -v curl &>/dev/null; then
     configuredClient="curl"
   elif command -v wget &>/dev/null; then
     configuredClient="wget"
@@ -55,42 +55,44 @@ getConfiguredClient()
 }
 
 ## Allows to call the users configured client without if statements everywhere
-httpGet()
-{
+httpGet() {
   case "${configuredClient}" in
-    curl)  curl -A curl -s "$@" ;;
-    wget)  wget -qO- "$@" ;;
-    httpie) http -b GET "$@" ;;
-    fetch) fetch -q "$@" ;;
-    *) ;;
+  curl) curl -A curl -s "$@" ;;
+  wget) wget -qO- "$@" ;;
+  httpie) http -b GET "$@" ;;
+  fetch) fetch -q "$@" ;;
+  *) ;;
   esac
 }
 
 ## uses openssl aes 256 cbc encryption to encrypt file salting it with password designated by user
-encrypt()
-{
+encrypt() {
   echo "Encrypting $1..."
-  openssl enc -aes-256-cbc -salt -a -in "$1" -out "$2" || { echo "File not found"; return 1; }
+  openssl enc -aes-256-cbc -salt -a -in "$1" -out "$2" || {
+    echo "File not found"
+    return 1
+  }
   echo "Successfully encrypted"
 }
 
 ## uses openssl aes 256 cbc decryption to decrypt file
-decrypt()
-{
+decrypt() {
   echo "Decrypting $1..."
-  openssl enc -aes-256-cbc -d -a -in "$1" -out "$2" || { echo "File not found"; return 1; }
+  openssl enc -aes-256-cbc -d -a -in "$1" -out "$2" || {
+    echo "File not found"
+    return 1
+  }
   echo "Successfully decrypted"
 }
 
-update()
-{
+update() {
   # Author: Alexander Epstein https://github.com/alexanderepstein
   # Update utility version 2.2.0
   # To test the tool enter in the defualt values that are in the examples for each variable
-  repositoryName="Bash-Snippets" #Name of repostiory to be updated ex. Sandman-Lite
-  githubUserName="alexanderepstein" #username that hosts the repostiory ex. alexanderepstein
-  nameOfInstallFile="install.sh" # change this if the installer file has a different name be sure to include file extension if there is one
-  latestVersion=$(httpGet https://api.github.com/repos/${githubUserName}/${repositoryName}/tags | grep -Eo '"name":.*?[^\\]",'| head -1 | grep -Eo "[0-9.]+" ) #always grabs the tag without the v option
+  repositoryName="Bash-Snippets"                                                                                                                               #Name of repostiory to be updated ex. Sandman-Lite
+  githubUserName="alexanderepstein"                                                                                                                            #username that hosts the repostiory ex. alexanderepstein
+  nameOfInstallFile="install.sh"                                                                                                                               # change this if the installer file has a different name be sure to include file extension if there is one
+  latestVersion=$(httpGet https://api.github.com/repos/${githubUserName}/${repositoryName}/tags | grep -Eo '"name":.*?[^\\]",' | head -1 | grep -Eo "[0-9.]+") #always grabs the tag without the v option
 
   if [[ ${currentVersion} == "" || ${repositoryName} == "" || ${githubUserName} == "" || ${nameOfInstallFile} == "" ]]; then
     echo "Error: update utility has not been configured correctly." >&2
@@ -104,19 +106,37 @@ update()
       echo -n "Do you wish to update ${repositoryName} [Y/n]: "
       read -r answer
       if [[ "${answer}" == [Yy] ]]; then
-        cd ~ || { echo 'Update Failed'; exit 1; }
-        if [[ -d  ~/${repositoryName} ]]; then rm -r -f "${repositoryName}" || { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
+        cd ~ || {
+          echo 'Update Failed'
+          exit 1
+        }
+        if [[ -d ~/${repositoryName} ]]; then rm -r -f "${repositoryName}" || {
+          echo "Permissions Error: try running the update as sudo"
+          exit 1
+        }; fi
         echo -n "Downloading latest version of: ${repositoryName}."
-        git clone -q "https://github.com/${githubUserName}/${repositoryName}" && touch .BSnippetsHiddenFile || { echo "Failure!"; exit 1; } &
-        while [[ ! -f .BSnippetsHiddenFile ]]; do { echo -n "."; sleep 2; };done
+        git clone -q "https://github.com/${githubUserName}/${repositoryName}" && touch .BSnippetsHiddenFile || {
+          echo "Failure!"
+          exit 1
+        } &
+        while [[ ! -f .BSnippetsHiddenFile ]]; do {
+          echo -n "."
+          sleep 2
+        }; done
         rm -f .BSnippetsHiddenFile
         echo "Success!"
-        cd "${repositoryName}" || { echo 'Update Failed'; exit 1; }
-        git checkout "v${latestVersion}" 2> /dev/null || git checkout "${latestVersion}" 2> /dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
+        cd "${repositoryName}" || {
+          echo 'Update Failed'
+          exit 1
+        }
+        git checkout "v${latestVersion}" 2>/dev/null || git checkout "${latestVersion}" 2>/dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
         chmod a+x install.sh #this might be necessary in your case but wasnt in mine.
         ./"${nameOfInstallFile}" "update" || exit 1
         cd ..
-        rm -r -f "${repositoryName}" || { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/${repositoryName} delete this directory with sudo"; exit 1; }
+        rm -r -f "${repositoryName}" || {
+          echo "Permissions Error: update succesfull but cannot delete temp files located at ~/${repositoryName} delete this directory with sudo"
+          exit 1
+        }
       else
         exit 1
       fi
@@ -126,9 +146,7 @@ update()
   fi
 }
 
-
-usage()
-{
+usage() {
   cat <<EOF
 Crypt
 Description: A wrapper around openssl that facilitates encrypting and decrypting files.
@@ -148,50 +166,54 @@ checkOpenSSL || exit 1
 
 while getopts "huve:d:" opt; do ## alows for using options in bash
   case ${opt} in
-    e)  ## when trying to encrypt run this
-        if [[ ${state} != "decrypt" ]]; then
-          state="encrypt"
-        else
-          echo "Error: the -d and -e options are mutally exclusive" >&2
-          exit 1
-        fi
-        if [[ $# -ne 3 ]]; then
-          echo "Option -e needs and only accepts two arguments [file to encrypt] [output file]" >&2
-          exit 1
-        fi
-        ;;
-    \?) echo "Invalid option: -${OPTARG}" >&2
-        exit 1
-        ;;
-    d)  ## when trying to decrypt run this
-        if [[ ${state} != "encrypt" ]]; then
-          state="decrypt"
-        else
-          echo "Error: the -e and -d options are mutally exclusive" >&2
-          exit 1
-        fi
-        if [[ $# -ne 3 ]]; then
-          echo "Option -d needs and only accepts two arguments [file to decrypt] [output file]" >&2
-          exit 1
-        fi
-        ;;
-    u)  getConfiguredClient || exit 1
-        checkInternet || exit 1
-        update
-        exit 0
-        ;;
-    h)  usage
-        exit 0
-        ;;
-    v)  echo "Version ${currentVersion}"
-        exit 0
-        ;;
-    :)  ## will run when no arguments are provided to to e or d options
-        echo "Option -${OPTARG} requires an argument." >&2
-        exit 1
-        ;;
-    *)
-      ;;
+  e) ## when trying to encrypt run this
+    if [[ ${state} != "decrypt" ]]; then
+      state="encrypt"
+    else
+      echo "Error: the -d and -e options are mutally exclusive" >&2
+      exit 1
+    fi
+    if [[ $# -ne 3 ]]; then
+      echo "Option -e needs and only accepts two arguments [file to encrypt] [output file]" >&2
+      exit 1
+    fi
+    ;;
+  \?)
+    echo "Invalid option: -${OPTARG}" >&2
+    exit 1
+    ;;
+  d) ## when trying to decrypt run this
+    if [[ ${state} != "encrypt" ]]; then
+      state="decrypt"
+    else
+      echo "Error: the -e and -d options are mutally exclusive" >&2
+      exit 1
+    fi
+    if [[ $# -ne 3 ]]; then
+      echo "Option -d needs and only accepts two arguments [file to decrypt] [output file]" >&2
+      exit 1
+    fi
+    ;;
+  u)
+    getConfiguredClient || exit 1
+    checkInternet || exit 1
+    update
+    exit 0
+    ;;
+  h)
+    usage
+    exit 0
+    ;;
+  v)
+    echo "Version ${currentVersion}"
+    exit 0
+    ;;
+  :) ## will run when no arguments are provided to to e or d options
+    echo "Option -${OPTARG} requires an argument." >&2
+    exit 1
+    ;;
+  *) ;;
+
   esac
 done
 
diff --git a/bin/cryptocurrency b/bin/cryptocurrency
--- a/bin/cryptocurrency
+++ b/bin/cryptocurrency
@@ -5,10 +5,10 @@
 # Bash strict mode
 # shellcheck disable=SC2154
 ([[ -n ${ZSH_EVAL_CONTEXT} && ${ZSH_EVAL_CONTEXT} =~ :file$ ]] ||
- [[ -n ${BASH_VERSION} ]] && (return 0 2>/dev/null)) && SOURCED=true || SOURCED=false
+  [[ -n ${BASH_VERSION} ]] && (return 0 2>/dev/null)) && SOURCED=true || SOURCED=false
 if ! ${SOURCED}; then
-  set -o errexit # same as set -e
-  set -o nounset # same as set -u
+  set -o errexit  # same as set -e
+  set -o nounset  # same as set -u
   set -o errtrace # same as set -E
   set -o pipefail
   set -o posix
@@ -17,7 +17,7 @@ if ! ${SOURCED}; then
   shopt -s extdebug
   IFS=$(printf '\n\t')
 fi
-# END Bash scrict mode
+# END Bash strict mode
 
 unset base
 unset exchangeTo
@@ -26,9 +26,8 @@ currentVersion="1.22.0"
 unset configuredClient
 
 ## This function determines which http get tool the system has installed and returns an error if there isnt one
-getConfiguredClient()
-{
-  if  command -v curl &>/dev/null; then
+getConfiguredClient() {
+  if command -v curl &>/dev/null; then
     configuredClient="curl"
   elif command -v wget &>/dev/null; then
     configuredClient="wget"
@@ -43,36 +42,33 @@ getConfiguredClient()
 }
 
 ## Allows to call the users configured client without if statements everywhere
-httpGet()
-{
+httpGet() {
   case "$configuredClient" in
-    curl)  curl -A curl -s "$@" ;;
-    wget)  wget -qO- "$@" ;;
-    httpie) http -b GET "$@" ;;
-    fetch) fetch -q "$@" ;;
+  curl) curl -A curl -s "$@" ;;
+  wget) wget -qO- "$@" ;;
+  httpie) http -b GET "$@" ;;
+  fetch) fetch -q "$@" ;;
   esac
 }
 
 ## Top 10 cryptocurrencies as base
-checkValidCurrency()
-{
-  if [[ $1 != "BTC" && $1 != "ETH" \
-      && $1 != "XRP" && $1 != "LTC" && $1 != "XEM" \
-      && $1 != "ETC" && $1 != "DASH" && $1 != "MIOTA" \
-      && $1 != "XMR" && $1 != "STRAT" && $1 != "BCH" ]]; then
+checkValidCurrency() {
+  if [[ $1 != "BTC" && $1 != "ETH" &&
+    $1 != "XRP" && $1 != "LTC" && $1 != "XEM" &&
+    $1 != "ETC" && $1 != "DASH" && $1 != "MIOTA" &&
+    $1 != "XMR" && $1 != "STRAT" && $1 != "BCH" ]]; then
     echo "1"
   else
     echo "0"
   fi
 }
 
-checkTargetCurrency()
-{
-  if [[ $1 != "AUD" && $1 != "BRL" \
-      && $1 != "CAD" && $1 != "CHF" && $1 != "CNY" \
-      && $1 != "EUR" && $1 != "GBP" && $1 != "HKD" \
-      && $1 != "IDR" && $1 != "INR" && $1 != "JPY" && $1 != "KRW" \
-      && $1 != "MXN" && $1 != "RUB" && $1 != "USD" ]]; then
+checkTargetCurrency() {
+  if [[ $1 != "AUD" && $1 != "BRL" &&
+    $1 != "CAD" && $1 != "CHF" && $1 != "CNY" &&
+    $1 != "EUR" && $1 != "GBP" && $1 != "HKD" &&
+    $1 != "IDR" && $1 != "INR" && $1 != "JPY" && $1 != "KRW" &&
+    $1 != "MXN" && $1 != "RUB" && $1 != "USD" ]]; then
     echo "1"
   else
     echo "0"
@@ -81,12 +77,11 @@ checkTargetCurrency()
 
 ## Grabs the base currency from the user and validates it with all the possible currency
 ## types available on the API and guides user through input (doesnt take in arguments)
-getBase()
-{
+getBase() {
   echo -n "What is the base currency: "
   read -r base
   base=$(echo $base | tr /a-z/ /A-Z/)
-  if [[ $(checkValidCurrency $base) == "1"  ]]; then
+  if [[ $(checkValidCurrency $base) == "1" ]]; then
     unset base
     echo "Invalid base currency"
     getBase
@@ -95,8 +90,7 @@ getBase()
 
 ## Checks base currency from the user and validates it with all the possible currency
 ## types available on the API (requires argument)
-checkBase()
-{
+checkBase() {
   base=$1
   base=$(echo $base | tr /a-z/ /A-Z/)
   if [[ $(checkValidCurrency $base) == "1" ]]; then
@@ -107,27 +101,25 @@ checkBase()
 }
 
 # Matches the symbol to the appropriate ids regarding the API calling.
-transformBase()
-{
+transformBase() {
   case "$base" in
-    "ETH") reqId="ethereum" ;;
-    "BTC") reqId="bitcoin" ;;
-    "XRP") reqId="ripple" ;;
-    "LTC") reqId="litecoin" ;;
-    "XEM") reqId="nem" ;;
-    "ETC") reqId="ethereum-classic" ;;
-    "DASH") reqId="dash" ;;
-    "MIOTA") reqId="iota" ;;
-    "XMR") reqId="monero" ;;
-    "STRAT") reqId="stratis" ;;
-    "BCH") reqId="bitcoin-cash" ;;
+  "ETH") reqId="ethereum" ;;
+  "BTC") reqId="bitcoin" ;;
+  "XRP") reqId="ripple" ;;
+  "LTC") reqId="litecoin" ;;
+  "XEM") reqId="nem" ;;
+  "ETC") reqId="ethereum-classic" ;;
+  "DASH") reqId="dash" ;;
+  "MIOTA") reqId="iota" ;;
+  "XMR") reqId="monero" ;;
+  "STRAT") reqId="stratis" ;;
+  "BCH") reqId="bitcoin-cash" ;;
   esac
 }
 
 ## Grabs the exchange to currency from the user and validates it with all the possible currency
 ## types available on the API and guides user through input (doesnt take in arguments)
-getExchangeTo()
-{
+getExchangeTo() {
   echo -n "What currency to exchange to: "
   read -r exchangeTo
   exchangeTo=$(echo $exchangeTo | tr /a-z/ /A-Z/)
@@ -140,8 +132,7 @@ getExchangeTo()
 
 ## Grabs the exchange to currency from the user and validates it with all the possible currency
 ## types available on the API (requires arguments)
-checkExchangeTo()
-{
+checkExchangeTo() {
   exchangeTo=$1
   exchangeTo=$(echo $exchangeTo | tr /a-z/ /A-Z/)
   if [[ $(checkTargetCurrency $exchangeTo) == "1" ]]; then
@@ -153,8 +144,7 @@ checkExchangeTo()
 
 ## Get the amount that will be exchanged and validate that the user has entered a number (decimals are allowed)
 ## doesnt take in argument, it guides user through input
-getAmount()
-{
+getAmount() {
   echo -n "What is the amount being exchanged: "
   read -r amount
   if [[ ! "$amount" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
@@ -166,8 +156,7 @@ getAmount()
 
 ## Get the amount that will be exchanged
 ## validate that the user has entered a number (decimals are allowed and requires argument)
-checkAmount()
-{
+checkAmount() {
   amount=$1
   if [[ ! "$amount" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
     echo "The amount has to be a number"
@@ -176,24 +165,25 @@ checkAmount()
   fi
 }
 
-checkInternet()
-{
-  httpGet github.com > /dev/null 2>&1 || { echo "Error: no active internet connection" >&2; return 1; } # query github with a get request
+checkInternet() {
+  httpGet github.com >/dev/null 2>&1 || {
+    echo "Error: no active internet connection" >&2
+    return 1
+  } # query github with a get request
 }
 
 ## Grabs the exchange rate and does the math for converting the currency
-convertCurrency()
-{
+convertCurrency() {
   exchangeTo=$(echo "$exchangeTo" | tr '[:upper:]' '[:lower:]')
-  exchangeRate=$(httpGet "https://api.coinmarketcap.com/v1/ticker/$reqId/?convert=$exchangeTo" | grep -Eo "\"price_$exchangeTo\": \"[0-9 .]*" | sed s/"\"price_$exchangeTo\": \""//g) > /dev/null
+  exchangeRate=$(httpGet "https://api.coinmarketcap.com/v1/ticker/$reqId/?convert=$exchangeTo" | grep -Eo "\"price_$exchangeTo\": \"[0-9 .]*" | sed s/"\"price_$exchangeTo\": \""//g) >/dev/null
   if ! command -v bc &>/dev/null; then
     oldRate=$exchangeRate
-    exchangeRate=$(echo $exchangeRate | grep -Eo "^[0-9]*" )
-    amount=$(echo $amount | grep -Eo "^[0-9]*" )
-    exchangeAmount=$(( $exchangeRate * $amount ))
+    exchangeRate=$(echo $exchangeRate | grep -Eo "^[0-9]*")
+    amount=$(echo $amount | grep -Eo "^[0-9]*")
+    exchangeAmount=$(($exchangeRate * $amount))
     exchangeRate=$oldRate
   else
-    exchangeAmount=$( echo "$exchangeRate * $amount" | bc )
+    exchangeAmount=$(echo "$exchangeRate * $amount" | bc)
   fi
   exchangeTo=$(echo "$exchangeTo" | tr '[:lower:]' '[:upper:]')
 
@@ -207,15 +197,14 @@ convertCurrency()
 EOF
 }
 
-update()
-{
+update() {
   # Author: Alexander Epstein https://github.com/alexanderepstein
   # Update utility version 2.2.0
   # To test the tool enter in the defualt values that are in the examples for each variable
-  repositoryName="Bash-Snippets" #Name of repostiory to be updated ex. Sandman-Lite
-  githubUserName="alexanderepstein" #username that hosts the repostiory ex. alexanderepstein
-  nameOfInstallFile="install.sh" # change this if the installer file has a different name be sure to include file extension if there is one
-  latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",'| head -1 | grep -Eo "[0-9.]+" ) #always grabs the tag without the v option
+  repositoryName="Bash-Snippets"                                                                                                                           #Name of repostiory to be updated ex. Sandman-Lite
+  githubUserName="alexanderepstein"                                                                                                                        #username that hosts the repostiory ex. alexanderepstein
+  nameOfInstallFile="install.sh"                                                                                                                           # change this if the installer file has a different name be sure to include file extension if there is one
+  latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",' | head -1 | grep -Eo "[0-9.]+") #always grabs the tag without the v option
 
   if [[ $currentVersion == "" || $repositoryName == "" || $githubUserName == "" || $nameOfInstallFile == "" ]]; then
     echo "Error: update utility has not been configured correctly." >&2
@@ -229,19 +218,37 @@ update()
       echo -n "Do you wish to update $repositoryName [Y/n]: "
       read -r answer
       if [[ "$answer" == [Yy] ]]; then
-        cd ~ || { echo 'Update Failed'; exit 1; }
-        if [[ -d  ~/$repositoryName ]]; then rm -r -f $repositoryName || { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
+        cd ~ || {
+          echo 'Update Failed'
+          exit 1
+        }
+        if [[ -d ~/$repositoryName ]]; then rm -r -f $repositoryName || {
+          echo "Permissions Error: try running the update as sudo"
+          exit 1
+        }; fi
         echo -n "Downloading latest version of: $repositoryName."
-        git clone -q "https://github.com/$githubUserName/$repositoryName" && touch .BSnippetsHiddenFile || { echo "Failure!"; exit 1; } &
-        while [ ! -f .BSnippetsHiddenFile ]; do { echo -n "."; sleep 2; };done
+        git clone -q "https://github.com/$githubUserName/$repositoryName" && touch .BSnippetsHiddenFile || {
+          echo "Failure!"
+          exit 1
+        } &
+        while [ ! -f .BSnippetsHiddenFile ]; do {
+          echo -n "."
+          sleep 2
+        }; done
         rm -f .BSnippetsHiddenFile
         echo "Success!"
-        cd $repositoryName || { echo 'Update Failed'; exit 1; }
-        git checkout "v$latestVersion" 2> /dev/null || git checkout "$latestVersion" 2> /dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
+        cd $repositoryName || {
+          echo 'Update Failed'
+          exit 1
+        }
+        git checkout "v$latestVersion" 2>/dev/null || git checkout "$latestVersion" 2>/dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
         chmod a+x install.sh #this might be necessary in your case but wasnt in mine.
         ./$nameOfInstallFile "update" || exit 1
         cd ..
-        rm -r -f $repositoryName || { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"; exit 1; }
+        rm -r -f $repositoryName || {
+          echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"
+          exit 1
+        }
       else
         exit 1
       fi
@@ -251,8 +258,7 @@ update()
   fi
 }
 
-usage()
-{
+usage() {
   cat <<EOF
 CryptoCurrency
 
@@ -268,47 +274,47 @@ Usage: cryptocurrency or cryptocurrency [flag] or cryptocurrency [flag] [arg]
 EOF
 }
 
-
-
-
 while getopts "of:uvh" opt; do
   case "$opt" in
-    \?) echo "Invalid option: -$OPTARG" >&2
-        exit 1
-        ;;
-    h)  usage
-        exit 0
-        ;;
-    f)
-        fiat=$OPTARG
-        ;;
-    o)
-        old="true"
-        ;;
-    v)  echo "Version $currentVersion"
-        exit 0
-        ;;
-    u)  checkInternet || exit 1 # check if we have a valid internet connection if this isnt true the rest of the script will not work so stop here
-        update
-        exit 0
-        ;;
-    :)  echo "Option -$OPTARG requires an argument." >&2
-        exit 1
-        ;;
+  \?)
+    echo "Invalid option: -$OPTARG" >&2
+    exit 1
+    ;;
+  h)
+    usage
+    exit 0
+    ;;
+  f)
+    fiat=$OPTARG
+    ;;
+  o)
+    old="true"
+    ;;
+  v)
+    echo "Version $currentVersion"
+    exit 0
+    ;;
+  u)
+    checkInternet || exit 1 # check if we have a valid internet connection if this isnt true the rest of the script will not work so stop here
+    update
+    exit 0
+    ;;
+  :)
+    echo "Option -$OPTARG requires an argument." >&2
+    exit 1
+    ;;
   esac
 done
 
-if $old;then
-getConfiguredClient || exit 1
-getBase # get base currency
-getExchangeTo # get exchange to currency
-getAmount # get the amount to be converted
-transformBase
-convertCurrency # grab the exhange rate and perform the conversion
-exit 0
+if $old; then
+  getConfiguredClient || exit 1
+  getBase       # get base currency
+  getExchangeTo # get exchange to currency
+  getAmount     # get the amount to be converted
+  transformBase
+  convertCurrency # grab the exhange rate and perform the conversion
+  exit 0
 fi
-
-
 
 if [[ $1 == "update" ]]; then
   getConfiguredClient || exit 1
diff --git a/bin/currency b/bin/currency
--- a/bin/currency
+++ b/bin/currency
@@ -4,10 +4,10 @@
 # Bash strict mode
 # shellcheck disable=SC2154
 ([[ -n ${ZSH_EVAL_CONTEXT} && ${ZSH_EVAL_CONTEXT} =~ :file$ ]] ||
- [[ -n ${BASH_VERSION} ]] && (return 0 2>/dev/null)) && SOURCED=true || SOURCED=false
+  [[ -n ${BASH_VERSION} ]] && (return 0 2>/dev/null)) && SOURCED=true || SOURCED=false
 if ! ${SOURCED}; then
-  set -o errexit # same as set -e
-  set -o nounset # same as set -u
+  set -o errexit  # same as set -e
+  set -o nounset  # same as set -u
   set -o errtrace # same as set -E
   set -o pipefail
   set -o posix
@@ -16,7 +16,7 @@ if ! ${SOURCED}; then
   shopt -s extdebug
   IFS=$(printf '\n\t')
 fi
-# END Bash scrict mode
+# END Bash strict mode
 
 unset base
 unset exchangeTo
@@ -27,36 +27,33 @@ currencyCodes=(AUD BGN BRL CAD CHF CNY CZK DKK
   JPY KRW MXN MYR NOK NZD PHP PLN
   RON RUB SEK SGD THB TRY USD ZAR)
 
-  ## This function determines which http get tool the system has installed and returns an error if there isnt one
-  getConfiguredClient()
-  {
-    if command -v curl &>/dev/null; then
-      configuredClient="curl"
-    elif command -v wget &>/dev/null; then
-      configuredClient="wget"
-    elif command -v http &>/dev/null; then
-      configuredClient="httpie"
-    elif command -v fetch &>/dev/null; then
-      configuredClient="fetch"
-    else
-      echo "Error: This tool reqires either curl, wget, httpie or fetch to be installed." >&2
-      return 1
-    fi
-  }
+## This function determines which http get tool the system has installed and returns an error if there isnt one
+getConfiguredClient() {
+  if command -v curl &>/dev/null; then
+    configuredClient="curl"
+  elif command -v wget &>/dev/null; then
+    configuredClient="wget"
+  elif command -v http &>/dev/null; then
+    configuredClient="httpie"
+  elif command -v fetch &>/dev/null; then
+    configuredClient="fetch"
+  else
+    echo "Error: This tool reqires either curl, wget, httpie or fetch to be installed." >&2
+    return 1
+  fi
+}
 
-  ## Allows to call the users configured client without if statements everywhere
-  httpGet()
-  {
-    case "$configuredClient" in
-      curl)  curl -A curl -s "$@" ;;
-      wget)  wget -qO- "$@" ;;
-      httpie) http -b GET "$@" ;;
-      fetch) fetch -q "$@" ;;
-    esac
-  }
+## Allows to call the users configured client without if statements everywhere
+httpGet() {
+  case "$configuredClient" in
+  curl) curl -A curl -s "$@" ;;
+  wget) wget -qO- "$@" ;;
+  httpie) http -b GET "$@" ;;
+  fetch) fetch -q "$@" ;;
+  esac
+}
 
-checkValidCurrency()
-{
+checkValidCurrency() {
   if [[ "${currencyCodes[*]}" == *"$(echo "${@}" | tr -d '[:space:]')"* ]]; then
     echo "0"
   else
@@ -66,8 +63,7 @@ checkValidCurrency()
 
 ## Grabs the base currency from the user and validates it with all the possible currency
 ## types available on the API and guides user through input (doesnt take in arguments)
-getBase()
-{
+getBase() {
   echo -n "What is the base currency: "
   read -r base
   base=$(echo $base | tr /a-z/ /A-Z/)
@@ -80,8 +76,7 @@ getBase()
 
 ## Checks base currency from the user and validates it with all the possible currency
 ## types available on the API (requires argument)
-checkBase()
-{
+checkBase() {
   base=$1
   base=$(echo $base | tr /a-z/ /A-Z/)
   if [[ $(checkValidCurrency $base) == "1" ]]; then
@@ -93,8 +88,7 @@ checkBase()
 
 ## Grabs the exchange to currency from the user and validates it with all the possible currency
 ## types available on the API and guides user through input (doesnt take in arguments)
-getExchangeTo()
-{
+getExchangeTo() {
   echo -n "What currency to exchange to: "
   read -r exchangeTo
   exchangeTo=$(echo $exchangeTo | tr /a-z/ /A-Z/)
@@ -107,8 +101,7 @@ getExchangeTo()
 
 ## Grabs the exchange to currency from the user and validates it with all the possible currency
 ## types available on the API (requires arguments)
-checkExchangeTo()
-{
+checkExchangeTo() {
   exchangeTo=$1
   exchangeTo=$(echo $exchangeTo | tr /a-z/ /A-Z/)
   if [[ $(checkValidCurrency $exchangeTo) == "1" ]]; then
@@ -120,12 +113,10 @@ checkExchangeTo()
 
 ## Get the amount that will be exchanged and validate that the user has entered a number (decimals are allowed)
 ## doesnt take in argument, it guides user through input
-getAmount()
-{
+getAmount() {
   echo -n "What is the amount being exchanged: "
   read -r amount
-  if [[ ! "$amount" =~ ^[0-9]+(\.[0-9]+)?$ ]]
-  then
+  if [[ ! "$amount" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
     echo "The amount has to be a number"
     unset amount
     getAmount
@@ -134,34 +125,33 @@ getAmount()
 
 ## Get the amount that will be exchanged
 ## validate that the user has entered a number (decimals are allowed and requires argument)
-checkAmount()
-{
+checkAmount() {
   amount=$1
-  if [[ ! "$amount" =~ ^[0-9]+(\.[0-9]+)?$ ]]
-  then
+  if [[ ! "$amount" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
     echo "The amount has to be a number"
     unset amount
     exit 1
   fi
 }
 
-checkInternet()
-{
-  httpGet github.com > /dev/null 2>&1 || { echo "Error: no active internet connection" >&2; return 1; } # query github with a get request
+checkInternet() {
+  httpGet github.com >/dev/null 2>&1 || {
+    echo "Error: no active internet connection" >&2
+    return 1
+  } # query github with a get request
 }
 
 ## Grabs the exchange rate and does the math for converting the currency
-convertCurrency()
-{
-  exchangeRate=$(httpGet "http://api.fixer.io/latest?base=$base&symbols=$exchangeTo" | grep -Eo "[0-9]*[.][0-9]*") > /dev/null
+convertCurrency() {
+  exchangeRate=$(httpGet "http://api.fixer.io/latest?base=$base&symbols=$exchangeTo" | grep -Eo "[0-9]*[.][0-9]*") >/dev/null
   if ! command -v bc &>/dev/null; then
     oldRate=$exchangeRate
-    exchangeRate=$(echo $exchangeRate | grep -Eo "^[0-9]*" )
-    amount=$(echo $amount | grep -Eo "^[0-9]*" )
-    exchangeAmount=$(( $exchangeRate * $amount ))
+    exchangeRate=$(echo $exchangeRate | grep -Eo "^[0-9]*")
+    amount=$(echo $amount | grep -Eo "^[0-9]*")
+    exchangeAmount=$(($exchangeRate * $amount))
     exchangeRate=$oldRate
   else
-    exchangeAmount=$( echo "$exchangeRate * $amount" | bc )
+    exchangeAmount=$(echo "$exchangeRate * $amount" | bc)
   fi
 
   cat <<EOF
@@ -175,15 +165,14 @@ convertCurrency()
 EOF
 }
 
-update()
-{
+update() {
   # Author: Alexander Epstein https://github.com/alexanderepstein
   # Update utility version 2.2.0
   # To test the tool enter in the defualt values that are in the examples for each variable
-  repositoryName="Bash-Snippets" #Name of repostiory to be updated ex. Sandman-Lite
-  githubUserName="alexanderepstein" #username that hosts the repostiory ex. alexanderepstein
-  nameOfInstallFile="install.sh" # change this if the installer file has a different name be sure to include file extension if there is one
-  latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",'| head -1 | grep -Eo "[0-9.]+" ) #always grabs the tag without the v option
+  repositoryName="Bash-Snippets"                                                                                                                           #Name of repostiory to be updated ex. Sandman-Lite
+  githubUserName="alexanderepstein"                                                                                                                        #username that hosts the repostiory ex. alexanderepstein
+  nameOfInstallFile="install.sh"                                                                                                                           # change this if the installer file has a different name be sure to include file extension if there is one
+  latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",' | head -1 | grep -Eo "[0-9.]+") #always grabs the tag without the v option
 
   if [[ $currentVersion == "" || $repositoryName == "" || $githubUserName == "" || $nameOfInstallFile == "" ]]; then
     echo "Error: update utility has not been configured correctly." >&2
@@ -197,19 +186,37 @@ update()
       echo -n "Do you wish to update $repositoryName [Y/n]: "
       read -r answer
       if [[ "$answer" == [Yy] ]]; then
-        cd ~ || { echo 'Update Failed'; exit 1; }
-        if [[ -d  ~/$repositoryName ]]; then rm -r -f $repositoryName || { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
+        cd ~ || {
+          echo 'Update Failed'
+          exit 1
+        }
+        if [[ -d ~/$repositoryName ]]; then rm -r -f $repositoryName || {
+          echo "Permissions Error: try running the update as sudo"
+          exit 1
+        }; fi
         echo -n "Downloading latest version of: $repositoryName."
-        git clone -q "https://github.com/$githubUserName/$repositoryName" && touch .BSnippetsHiddenFile || { echo "Failure!"; exit 1; } &
-        while [ ! -f .BSnippetsHiddenFile ]; do { echo -n "."; sleep 2; };done
+        git clone -q "https://github.com/$githubUserName/$repositoryName" && touch .BSnippetsHiddenFile || {
+          echo "Failure!"
+          exit 1
+        } &
+        while [ ! -f .BSnippetsHiddenFile ]; do {
+          echo -n "."
+          sleep 2
+        }; done
         rm -f .BSnippetsHiddenFile
         echo "Success!"
-        cd $repositoryName || { echo 'Update Failed'; exit 1; }
-        git checkout "v$latestVersion" 2> /dev/null || git checkout "$latestVersion" 2> /dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
+        cd $repositoryName || {
+          echo 'Update Failed'
+          exit 1
+        }
+        git checkout "v$latestVersion" 2>/dev/null || git checkout "$latestVersion" 2>/dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
         chmod a+x install.sh #this might be necessary in your case but wasnt in mine.
         ./$nameOfInstallFile "update" || exit 1
         cd ..
-        rm -r -f $repositoryName || { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"; exit 1; }
+        rm -r -f $repositoryName || {
+          echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"
+          exit 1
+        }
       else
         exit 1
       fi
@@ -219,9 +226,7 @@ update()
   fi
 }
 
-
-usage()
-{
+usage() {
   cat <<EOF
 Currency
 Description: A realtime currency converter.
@@ -249,34 +254,38 @@ EOF
 
 getConfiguredClient || exit 1
 
-
 while getopts "uvh" opt; do
   case "$opt" in
-    \?) echo "Invalid option: -$OPTARG" >&2
-        exit 1
-        ;;
-    h)  usage
-        exit 0
-        ;;
-    v)  echo "Version $currentVersion"
-        exit 0
-        ;;
-    u)  checkInternet || exit 1 # check if we have a valid internet connection if this isnt true the rest of the script will not work so stop here
-        update
-        exit 0
-        ;;
-    :)  echo "Option -$OPTARG requires an argument." >&2
-        exit 1
-        ;;
+  \?)
+    echo "Invalid option: -$OPTARG" >&2
+    exit 1
+    ;;
+  h)
+    usage
+    exit 0
+    ;;
+  v)
+    echo "Version $currentVersion"
+    exit 0
+    ;;
+  u)
+    checkInternet || exit 1 # check if we have a valid internet connection if this isnt true the rest of the script will not work so stop here
+    update
+    exit 0
+    ;;
+  :)
+    echo "Option -$OPTARG requires an argument." >&2
+    exit 1
+    ;;
   esac
 done
 
 if [[ $# == 0 ]]; then
   checkInternet || exit 1 # check if we have a valid internet connection if this isnt true the rest of the script will not work so stop here
-  getBase # get base currency
-  getExchangeTo # get exchange to currency
-  getAmount # get the amount to be converted
-  convertCurrency # grab the exhange rate and perform the conversion
+  getBase                 # get base currency
+  getExchangeTo           # get exchange to currency
+  getAmount               # get the amount to be converted
+  convertCurrency         # grab the exhange rate and perform the conversion
   exit 0
 elif [[ $# == "1" ]]; then
   if [[ $1 == "update" ]]; then
diff --git a/bin/geo b/bin/geo
--- a/bin/geo
+++ b/bin/geo
@@ -7,10 +7,9 @@
 currentVersion="1.22.0"
 configuredClient=""
 
-## This function determines which http get tool the system has installed and returns an error if there isnt one
-getConfiguredClient()
-{
-  if  command -v curl &>/dev/null; then
+## This function determines which http get tool the system has installed and returns an error if there isn't one
+getConfiguredClient() {
+  if command -v curl &>/dev/null; then
     configuredClient="curl"
   elif command -v wget &>/dev/null; then
     configuredClient="wget"
@@ -25,13 +24,12 @@ getConfiguredClient()
 }
 
 ## Allows to call the users configured client without if statements everywhere
-httpGet()
-{
+httpGet() {
   case "$configuredClient" in
-    curl)  curl -A curl -s "$@" ;;
-    wget)  wget -qO- "$@" ;;
-    httpie) http -b GET "$@" ;;
-    fetch) fetch -q "$@" ;;
+  curl) curl -A curl -s "$@" ;;
+  wget) wget -qO- "$@" ;;
+  httpie) http -b GET "$@" ;;
+  fetch) fetch -q "$@" ;;
   esac
 }
 
@@ -58,7 +56,7 @@ Example: geo -a 8.8.8.8 -o city,zip,isp
   -h            Returns Help Screen
   -u            Updates Bash-Snippets
 EOF
-    exit
+  exit
 }
 
 # Displays version number
@@ -98,7 +96,7 @@ router_search() {
 # Fetches DNS nameserver
 dns_search() {
   if [ "$(uname)" = "Darwin" ]; then
-    grep -i nameserver /etc/resolv.conf |head -n1|cut -d ' ' -f2
+    grep -i nameserver /etc/resolv.conf | head -n1 | cut -d ' ' -f2
   elif [ "$(uname -s)" = "Linux" ]; then
     cat /etc/resolv.conf | grep -i ^nameserver | cut -d ' ' -f2
   else
@@ -133,15 +131,14 @@ specific_geo() {
   fi
 }
 
-update()
-{
+update() {
   # Author: Alexander Epstein https://github.com/alexanderepstein
   # Update utility version 2.2.0
   # To test the tool enter in the defualt values that are in the examples for each variable
-  repositoryName="Bash-Snippets" #Name of repostiory to be updated ex. Sandman-Lite
-  githubUserName="alexanderepstein" #username that hosts the repostiory ex. alexanderepstein
-  nameOfInstallFile="install.sh" # change this if the installer file has a different name be sure to include file extension if there is one
-  latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",'| head -1 | grep -Eo "[0-9.]+" ) #always grabs the tag without the v option
+  repositoryName="Bash-Snippets"                                                                                                                           #Name of repostiory to be updated ex. Sandman-Lite
+  githubUserName="alexanderepstein"                                                                                                                        #username that hosts the repostiory ex. alexanderepstein
+  nameOfInstallFile="install.sh"                                                                                                                           # change this if the installer file has a different name be sure to include file extension if there is one
+  latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",' | head -1 | grep -Eo "[0-9.]+") #always grabs the tag without the v option
 
   if [[ $currentVersion == "" || $repositoryName == "" || $githubUserName == "" || $nameOfInstallFile == "" ]]; then
     echo "Error: update utility has not been configured correctly." >&2
@@ -155,19 +152,37 @@ update()
       echo -n "Do you wish to update $repositoryName [Y/n]: "
       read -r answer
       if [[ "$answer" == [Yy] ]]; then
-        cd ~ || { echo 'Update Failed'; exit 1; }
-        if [[ -d  ~/$repositoryName ]]; then rm -r -f $repositoryName || { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
+        cd ~ || {
+          echo 'Update Failed'
+          exit 1
+        }
+        if [[ -d ~/$repositoryName ]]; then rm -r -f $repositoryName || {
+          echo "Permissions Error: try running the update as sudo"
+          exit 1
+        }; fi
         echo -n "Downloading latest version of: $repositoryName."
-        git clone -q "https://github.com/$githubUserName/$repositoryName" && touch .BSnippetsHiddenFile || { echo "Failure!"; exit 1; } &
-        while [ ! -f .BSnippetsHiddenFile ]; do { echo -n "."; sleep 2; };done
+        git clone -q "https://github.com/$githubUserName/$repositoryName" && touch .BSnippetsHiddenFile || {
+          echo "Failure!"
+          exit 1
+        } &
+        while [ ! -f .BSnippetsHiddenFile ]; do {
+          echo -n "."
+          sleep 2
+        }; done
         rm -f .BSnippetsHiddenFile
         echo "Success!"
-        cd $repositoryName || { echo 'Update Failed'; exit 1; }
-        git checkout "v$latestVersion" 2> /dev/null || git checkout "$latestVersion" 2> /dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
+        cd $repositoryName || {
+          echo 'Update Failed'
+          exit 1
+        }
+        git checkout "v$latestVersion" 2>/dev/null || git checkout "$latestVersion" 2>/dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
         chmod a+x install.sh #this might be necessary in your case but wasnt in mine.
         ./$nameOfInstallFile "update" || exit 1
         cd ..
-        rm -r -f $repositoryName || { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"; exit 1; }
+        rm -r -f $repositoryName || {
+          echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"
+          exit 1
+        }
       else
         exit 1
       fi
@@ -178,25 +193,28 @@ update()
 }
 
 checkInternet() {
-  httpGet github.com > /dev/null 2>&1 || { echo "Error: no active internet connection" >&2; return 1; } # query github with a get request
+  httpGet github.com >/dev/null 2>&1 || {
+    echo "Error: no active internet connection" >&2
+    return 1
+  } # query github with a get request
 }
 
 # Option parsing "controller"
 optspec="uwlrdm:go:a:vh*:"
 while getopts "$optspec" optchar; do
   case "${optchar}" in
-    w) getConfiguredClient && checkInternet && wan_search || exit 1 ;;
-    l) lan_search ;;
-    r) router_search ;;
-    d) dns_search ;;
-    m) MAC=$OPTARG mac_search ;;
-    g) getConfiguredClient && checkInternet && geodata_search || exit 1 ;;
-    a) ADDRESS=$OPTARG ;;
-    o) getConfiguredClient && checkInternet && OPTIONS=$OPTARG specific_geo || exit 1 ;;
-    v) version ;;
-    h) usage ;;
-    u) getConfiguredClient && checkInternet && update || exit 1 ;;
-    *) usage ;;
+  w) getConfiguredClient && checkInternet && wan_search || exit 1 ;;
+  l) lan_search ;;
+  r) router_search ;;
+  d) dns_search ;;
+  m) MAC=$OPTARG mac_search ;;
+  g) getConfiguredClient && checkInternet && geodata_search || exit 1 ;;
+  a) ADDRESS=$OPTARG ;;
+  o) getConfiguredClient && checkInternet && OPTIONS=$OPTARG specific_geo || exit 1 ;;
+  v) version ;;
+  h) usage ;;
+  u) getConfiguredClient && checkInternet && update || exit 1 ;;
+  *) usage ;;
   esac
 done
 
diff --git a/bin/lyrics b/bin/lyrics
--- a/bin/lyrics
+++ b/bin/lyrics
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
 # Author: Alexander Epstein https://github.com/alexanderepstein
+
 currentVersion="1.22.0"
 configuredClient=""
 artist="false"
@@ -7,9 +8,8 @@ song="false"
 filePath=""
 
 ## This function determines which http get tool the system has installed and returns an error if there isnt one
-getConfiguredClient()
-{
-  if  command -v curl &>/dev/null; then
+getConfiguredClient() {
+  if command -v curl &>/dev/null; then
     configuredClient="curl"
   elif command -v wget &>/dev/null; then
     configuredClient="wget"
@@ -23,11 +23,10 @@ getConfiguredClient()
   fi
 }
 
-getConfiguredPython()
-{
-  if  command -v python2 &>/dev/null ; then
+getConfiguredPython() {
+  if command -v python2 &>/dev/null; then
     configuredPython="python2"
-  elif command -v python &>/dev/null ; then
+  elif command -v python &>/dev/null; then
     configuredPython="python"
   else
     echo "Error: This tool requires python 2 to be installed."
@@ -36,36 +35,32 @@ getConfiguredPython()
 }
 
 if [[ $(uname) != "Darwin" ]]; then
-  python()
-  {
+  python() {
     case "$configuredPython" in
-      python2) python2 "$@";;
-      python) python "$@";;
+    python2) python2 "$@" ;;
+    python) python "$@" ;;
     esac
   }
 fi
 
-
 ## Allows to call the users configured client without if statements everywhere
-httpGet()
-{
+httpGet() {
   case "$configuredClient" in
-    curl)  curl -A curl -s "$@" ;;
-    wget)  wget -qO- "$@" ;;
-    httpie) http -b GET "$@" ;;
-    fetch) fetch -q "$@" ;;
+  curl) curl -A curl -s "$@" ;;
+  wget) wget -qO- "$@" ;;
+  httpie) http -b GET "$@" ;;
+  fetch) fetch -q "$@" ;;
   esac
 }
 
-update()
-{
+update() {
   # Author: Alexander Epstein https://github.com/alexanderepstein
   # Update utility version 1.2.0
   # To test the tool enter in the defualt values that are in the examples for each variable
-  repositoryName="Bash-Snippets" #Name of repostiory to be updated ex. Sandman-Lite
-  githubUserName="alexanderepstein" #username that hosts the repostiory ex. alexanderepstein
-  nameOfInstallFile="install.sh" # change this if the installer file has a different name be sure to include file extension if there is one
-  latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",'| head -1 | grep -Eo "[0-9.]+" ) #always grabs the tag without the v option
+  repositoryName="Bash-Snippets"                                                                                                                           #Name of repostiory to be updated ex. Sandman-Lite
+  githubUserName="alexanderepstein"                                                                                                                        #username that hosts the repostiory ex. alexanderepstein
+  nameOfInstallFile="install.sh"                                                                                                                           # change this if the installer file has a different name be sure to include file extension if there is one
+  latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",' | head -1 | grep -Eo "[0-9.]+") #always grabs the tag without the v option
 
   if [[ $currentVersion == "" || $repositoryName == "" || $githubUserName == "" || $nameOfInstallFile == "" ]]; then
     echo "Error: update utility has not been configured correctly." >&2
@@ -79,15 +74,30 @@ update()
       echo -n "Do you wish to update $repositoryName [Y/n]: "
       read -r answer
       if [[ "$answer" == [Yy] ]]; then
-        cd ~ || { echo 'Update Failed'; exit 1; }
-        if [[ -d  ~/$repositoryName ]]; then rm -r -f $repositoryName || { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
-        git clone "https://github.com/$githubUserName/$repositoryName" || { echo "Couldn't download latest version"; exit 1; }
-        cd $repositoryName || { echo 'Update Failed'; exit 1; }
-        git checkout "v$latestVersion" 2> /dev/null || git checkout "$latestVersion" 2> /dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
+        cd ~ || {
+          echo 'Update Failed'
+          exit 1
+        }
+        if [[ -d ~/$repositoryName ]]; then rm -r -f $repositoryName || {
+          echo "Permissions Error: try running the update as sudo"
+          exit 1
+        }; fi
+        git clone "https://github.com/$githubUserName/$repositoryName" || {
+          echo "Couldn't download latest version"
+          exit 1
+        }
+        cd $repositoryName || {
+          echo 'Update Failed'
+          exit 1
+        }
+        git checkout "v$latestVersion" 2>/dev/null || git checkout "$latestVersion" 2>/dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
         chmod a+x install.sh #this might be necessary in your case but wasnt in mine.
         ./$nameOfInstallFile "update" || exit 1
         cd ..
-        rm -r -f $repositoryName || { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"; exit 1; }
+        rm -r -f $repositoryName || {
+          echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"
+          exit 1
+        }
       else
         exit 1
       fi
@@ -97,38 +107,41 @@ update()
   fi
 }
 
-checkInternet()
-{
-  httpGet github.com > /dev/null 2>&1 || { echo "Error: no active internet connection" >&2; return 1; } # query github with a get request
+checkInternet() {
+  httpGet github.com >/dev/null 2>&1 || {
+    echo "Error: no active internet connection" >&2
+    return 1
+  } # query github with a get request
 }
 
-getLyrics()
-{
+getLyrics() {
   encodedArtist=$(echo $1 | sed s/" "/%20/g | sed s/"&"/%26/g | sed s/,/%2C/g | sed s/-/%2D/g)
   encodedSong=$(echo $2 | sed s/" "/%20/g | sed s/"&"/%26/g | sed s/,/%2C/g | sed s/-/%2D/g)
   response=$(httpGet "https://api.lyrics.ovh/v1/$encodedArtist/$encodedSong")
-  lyrics=$(echo $response | python -c "import sys, json; print json.load(sys.stdin)['lyrics']" 2> /dev/null)
-  if [[ $lyrics == "" ]];then { echo "Error: no lyrics found!"; return 1; }; fi
+  lyrics=$(echo $response | python -c "import sys, json; print json.load(sys.stdin)['lyrics']" 2>/dev/null)
+  if [[ $lyrics == "" ]]; then {
+    echo "Error: no lyrics found!"
+    return 1
+  }; fi
 }
 
-printLyrics()
-{
-  if [[ $filePath == "" ]];then echo -e "$lyrics"
+printLyrics() {
+  if [[ $filePath == "" ]]; then
+    echo -e "$lyrics"
   else
-    if [ -f "$filePath" ];then
+    if [ -f "$filePath" ]; then
       echo -n "File already exists, do you want to overwrite it [Y/n]: "
       read -r answer
       if [[ "$answer" == [Yy] ]]; then
-        echo -e "$lyrics" > "$filePath";
+        echo -e "$lyrics" >"$filePath"
       fi
     else
-        echo -e "$lyrics" > "$filePath";
+      echo -e "$lyrics" >"$filePath"
     fi
-   fi
+  fi
 }
 
-usage()
-{
+usage() {
   cat <<EOF
 Lyrics
 Description: Fetch lyrics for a certain song.
@@ -145,40 +158,43 @@ Examples:
 EOF
 }
 
-
 while getopts "f:a:s:uvh" opt; do
   case "$opt" in
-    \?) echo "Invalid option: -$OPTARG" >&2
-        exit 1
-        ;;
-    h)  usage
-        exit 0
-        ;;
-    v)  echo "Version $currentVersion"
-        exit 0
-        ;;
-    u)
-        getConfiguredClient || exit 1
-        checkInternet || exit 1
-        update
-        exit 0
-        ;;
-    f)
-       filePath="$OPTARG"
-        ;;
-    a)
-        artist="true"
-        if [[ "$(echo "$@" | grep -Eo "\-s")" == "-s" ]];then song="true";fi # wont go through both options if arg spaced and not quoted this solves that issue (dont need this but once had bug on system where it was necessary)
-        if [[ "$(echo "$@" | grep -Eo "\-f")" == "-f" ]];then filePath=$(echo "$@" | grep -Eo "\-f [ a-z A-Z / 0-9 . \ ]*[ -]?" | sed s/-f//g | sed s/-//g | sed s/^" "//g);fi
-      ;;
-    s)
-        song="true"
-        if [[ "$(echo "$@" | grep -Eo "\-a")" == "-a" ]];then artist="true";fi # wont go through both options if arg spaced and not quoted this solves that issue (dont need this but once had bug on system where it was necessary)
-        if [[ "$(echo "$@" | grep -Eo "\-f")" == "-f" ]];then filePath=$(echo "$@" | grep -Eo "\-f [ a-z A-Z / 0-9 . \ ]*[ -]?" | sed s/-f//g | sed s/-//g | sed s/^" "//g);fi
-      ;;
-    :)  echo "Option -$OPTARG requires an argument." >&2
-        exit 1
-        ;;
+  \?)
+    echo "Invalid option: -$OPTARG" >&2
+    exit 1
+    ;;
+  h)
+    usage
+    exit 0
+    ;;
+  v)
+    echo "Version $currentVersion"
+    exit 0
+    ;;
+  u)
+    getConfiguredClient || exit 1
+    checkInternet || exit 1
+    update
+    exit 0
+    ;;
+  f)
+    filePath="$OPTARG"
+    ;;
+  a)
+    artist="true"
+    if [[ "$(echo "$@" | grep -Eo "\-s")" == "-s" ]]; then song="true"; fi # wont go through both options if arg spaced and not quoted this solves that issue (dont need this but once had bug on system where it was necessary)
+    if [[ "$(echo "$@" | grep -Eo "\-f")" == "-f" ]]; then filePath=$(echo "$@" | grep -Eo "\-f [ a-z A-Z / 0-9 . \ ]*[ -]?" | sed s/-f//g | sed s/-//g | sed s/^" "//g); fi
+    ;;
+  s)
+    song="true"
+    if [[ "$(echo "$@" | grep -Eo "\-a")" == "-a" ]]; then artist="true"; fi # wont go through both options if arg spaced and not quoted this solves that issue (dont need this but once had bug on system where it was necessary)
+    if [[ "$(echo "$@" | grep -Eo "\-f")" == "-f" ]]; then filePath=$(echo "$@" | grep -Eo "\-f [ a-z A-Z / 0-9 . \ ]*[ -]?" | sed s/-f//g | sed s/-//g | sed s/^" "//g); fi
+    ;;
+  :)
+    echo "Option -$OPTARG requires an argument." >&2
+    exit 1
+    ;;
   esac
 done
 
@@ -198,21 +214,32 @@ elif [[ $# == "1" ]]; then
   fi
 fi
 
-if ($artist && ! $song)  || ($song && ! $artist);then
+if ($artist && ! $song) || ($song && ! $artist); then
   echo "Error: the -a and the -s flag must be used to fetch lyrics."
   exit 1
-elif $artist && $song;then
+elif $artist && $song; then
   song=$(echo "$@" | grep -Eo "\-s [ a-z A-Z 0-9 . \ ]*[ -]?" | sed s/-s//g | sed s/-//g | sed s/^" "//g)
-  if [[ $song == "" ]];then { echo "Error: song could not be parsed from input."; exit 1; };fi
+  if [[ $song == "" ]]; then {
+    echo "Error: song could not be parsed from input."
+    exit 1
+  }; fi
   artist=$(echo "$@" | grep -Eo "\-a [ a-z A-Z 0-9 . \ ]*[ -]?" | sed s/-a//g | sed s/-//g | sed s/^" "//g)
-  if [[ $artist == "" ]];then { echo "Error: artist could not be parsed from input."; exit 1; };fi
+  if [[ $artist == "" ]]; then {
+    echo "Error: artist could not be parsed from input."
+    exit 1
+  }; fi
   getConfiguredClient || exit 1
-  if [[ $(uname) != "Darwin" ]]; then getConfiguredPython || exit 1;fi
+  if [[ $(uname) != "Darwin" ]]; then getConfiguredPython || exit 1; fi
   checkInternet || exit 1
   getLyrics "$artist" "$song" || exit 1
   printLyrics
 else
-  { clear; echo "You shouldnt be here but maaaaaaybeee you slipped passed me, learn to use the tool!"; sleep 5; clear;}
+  {
+    clear
+    echo "You shouldnt be here but maaaaaaybeee you slipped passed me, learn to use the tool!"
+    sleep 5
+    clear
+  }
   usage
   exit 1
 fi
