refactor: Mass reformat with shfmt

diff --git a/bin/movies b/bin/movies
--- a/bin/movies
+++ b/bin/movies
@@ -7,9 +7,8 @@ configuredPython=""
 detail=false
 
 ## This function determines which http get tool the system has installed and returns an error if there isnt one
-getConfiguredClient()
-{
-  if  command -v curl &>/dev/null; then
+getConfiguredClient() {
+  if command -v curl &>/dev/null; then
     configuredClient="curl"
   elif command -v wget &>/dev/null; then
     configuredClient="wget"
@@ -24,21 +23,19 @@ getConfiguredClient()
 }
 
 ## Allows to call the users configured client without if statements everywhere
-httpGet()
-{
+httpGet() {
   case "$configuredClient" in
-    curl)  curl -A curl -s "$@" ;;
-    wget)  wget -qO- "$@" ;;
-    httpie) http -b GET "$@" ;;
-    fetch) fetch -q "$@" ;;
+  curl) curl -A curl -s "$@" ;;
+  wget) wget -qO- "$@" ;;
+  httpie) http -b GET "$@" ;;
+  fetch) fetch -q "$@" ;;
   esac
 }
 
-getConfiguredPython()
-{
-  if  command -v python2 &>/dev/null ; then
+getConfiguredPython() {
+  if command -v python2 &>/dev/null; then
     configuredPython="python2"
-  elif command -v python &>/dev/null ; then
+  elif command -v python &>/dev/null; then
     configuredPython="python"
   else
     echo "Error: This tool requires python 2 to be installed."
@@ -47,50 +44,52 @@ getConfiguredPython()
 }
 
 if [[ $(uname) != "Darwin" ]]; then
-  python()
-  {
+  python() {
     case "$configuredPython" in
-      python2) python2 "$@";;
-      python) python "$@";;
+    python2) python2 "$@" ;;
+    python) python "$@" ;;
     esac
   }
 fi
 
-checkInternet()
-{
-  httpGet github.com > /dev/null 2>&1 || { echo "Error: no active internet connection" >&2; return 1; } # query github with a get request
+checkInternet() {
+  httpGet github.com >/dev/null 2>&1 || {
+    echo "Error: no active internet connection" >&2
+    return 1
+  } # query github with a get request
 }
 
 ## This function grabs information about a movie and using python parses the
 ## JSON response to extrapolate the information for storage
-getMovieInfo()
-{
-  apiKey=946f500a # try not to abuse this it is a key that came from the ruby-scripts repo I link to.
-  movie=$( (echo "$@" | tr " " + ) | sed 's/-d+//g' ) ## format the inputs to use for the api. Added sed command to filter -d flag.
-  export PYTHONIOENCODING=utf8 #necessary for python in some cases
-  movieInfo=$(httpGet "http://www.omdbapi.com/?t=$movie&apikey=$apiKey") > /dev/null # query the server and get the JSON response
-  checkResponse=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Response']" 2> /dev/null)
-  if [[ $checkResponse == "False" ]]; then { echo "No movie found" ; return 1 ;} fi ## check to see if the movie was found
+getMovieInfo() {
+  apiKey=946f500a                                                                   # try not to abuse this it is a key that came from the ruby-scripts repo I link to.
+  movie=$( (echo "$@" | tr " " +) | sed 's/-d+//g')                                 ## format the inputs to use for the api. Added sed command to filter -d flag.
+  export PYTHONIOENCODING=utf8                                                      #necessary for python in some cases
+  movieInfo=$(httpGet "http://www.omdbapi.com/?t=$movie&apikey=$apiKey") >/dev/null # query the server and get the JSON response
+  checkResponse=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Response']" 2>/dev/null)
+  if [[ $checkResponse == "False" ]]; then {
+    echo "No movie found"
+    return 1
+  }; fi ## check to see if the movie was found
   # The rest of the code is just extrapolating the data with python from the JSON response
-  title=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Title']" 2> /dev/null)
-  year=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Year']" 2> /dev/null)
-  runtime=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Runtime']" 2> /dev/null)
-  imdbScore=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Ratings'][0]['Value']" 2> /dev/null)
-  tomatoScore=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Ratings'][1]['Value']" 2> /dev/null)
-  metacriticScore=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Ratings'][2]['Value']" 2> /dev/null)
-  rated=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Rated']" 2> /dev/null)
-  genre=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Genre']" 2> /dev/null)
-  director=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Director']" 2> /dev/null)
-  production=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Production']" 2> /dev/null)
-  boxOffice=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['BoxOffice']" 2> /dev/null)
-  actors=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Actors']" 2> /dev/null)
-  plot=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Plot']" 2> /dev/null)
-  awards=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Awards']" 2> /dev/null)
+  title=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Title']" 2>/dev/null)
+  year=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Year']" 2>/dev/null)
+  runtime=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Runtime']" 2>/dev/null)
+  imdbScore=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Ratings'][0]['Value']" 2>/dev/null)
+  tomatoScore=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Ratings'][1]['Value']" 2>/dev/null)
+  metacriticScore=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Ratings'][2]['Value']" 2>/dev/null)
+  rated=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Rated']" 2>/dev/null)
+  genre=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Genre']" 2>/dev/null)
+  director=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Director']" 2>/dev/null)
+  production=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Production']" 2>/dev/null)
+  boxOffice=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['BoxOffice']" 2>/dev/null)
+  actors=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Actors']" 2>/dev/null)
+  plot=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Plot']" 2>/dev/null)
+  awards=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Awards']" 2>/dev/null)
 }
 
 # Prints the movie information out in a human readable format
-printMovieInfo()
-{
+printMovieInfo() {
   echo
   echo '=================================================='
   echo "| Title: $title"
@@ -115,15 +114,14 @@ printMovieInfo()
   echo
 }
 
-update()
-{
+update() {
   # Author: Alexander Epstein https://github.com/alexanderepstein
   # Update utility version 2.2.0
   # To test the tool enter in the defualt values that are in the examples for each variable
-  repositoryName="Bash-Snippets" #Name of repostiory to be updated ex. Sandman-Lite
-  githubUserName="alexanderepstein" #username that hosts the repostiory ex. alexanderepstein
-  nameOfInstallFile="install.sh" # change this if the installer file has a different name be sure to include file extension if there is one
-  latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",'| head -1 | grep -Eo "[0-9.]+" ) #always grabs the tag without the v option
+  repositoryName="Bash-Snippets"                                                                                                                           #Name of repostiory to be updated ex. Sandman-Lite
+  githubUserName="alexanderepstein"                                                                                                                        #username that hosts the repostiory ex. alexanderepstein
+  nameOfInstallFile="install.sh"                                                                                                                           # change this if the installer file has a different name be sure to include file extension if there is one
+  latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",' | head -1 | grep -Eo "[0-9.]+") #always grabs the tag without the v option
 
   if [[ $currentVersion == "" || $repositoryName == "" || $githubUserName == "" || $nameOfInstallFile == "" ]]; then
     echo "Error: update utility has not been configured correctly." >&2
@@ -137,19 +135,37 @@ update()
       echo -n "Do you wish to update $repositoryName [Y/n]: "
       read -r answer
       if [[ "$answer" == [Yy] ]]; then
-        cd ~ || { echo 'Update Failed'; exit 1; }
-        if [[ -d  ~/$repositoryName ]]; then rm -r -f $repositoryName || { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
+        cd ~ || {
+          echo 'Update Failed'
+          exit 1
+        }
+        if [[ -d ~/$repositoryName ]]; then rm -r -f $repositoryName || {
+          echo "Permissions Error: try running the update as sudo"
+          exit 1
+        }; fi
         echo -n "Downloading latest version of: $repositoryName."
-        git clone -q "https://github.com/$githubUserName/$repositoryName" && touch .BSnippetsHiddenFile || { echo "Failure!"; exit 1; } &
-        while [ ! -f .BSnippetsHiddenFile ]; do { echo -n "."; sleep 2; };done
+        git clone -q "https://github.com/$githubUserName/$repositoryName" && touch .BSnippetsHiddenFile || {
+          echo "Failure!"
+          exit 1
+        } &
+        while [ ! -f .BSnippetsHiddenFile ]; do {
+          echo -n "."
+          sleep 2
+        }; done
         rm -f .BSnippetsHiddenFile
         echo "Success!"
-        cd $repositoryName || { echo 'Update Failed'; exit 1; }
-        git checkout "v$latestVersion" 2> /dev/null || git checkout "$latestVersion" 2> /dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
+        cd $repositoryName || {
+          echo 'Update Failed'
+          exit 1
+        }
+        git checkout "v$latestVersion" 2>/dev/null || git checkout "$latestVersion" 2>/dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
         chmod a+x install.sh #this might be necessary in your case but wasnt in mine.
         ./$nameOfInstallFile "update" || exit 1
         cd ..
-        rm -r -f $repositoryName || { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"; exit 1; }
+        rm -r -f $repositoryName || {
+          echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"
+          exit 1
+        }
       else
         exit 1
       fi
@@ -159,8 +175,7 @@ update()
   fi
 }
 
-usage()
-{
+usage() {
   cat <<EOF
 Movies
 Description: Provides relevant information about a certain movie.
@@ -178,20 +193,27 @@ EOF
 if [[ $(uname) != "Darwin" ]]; then getConfiguredPython || exit 1; fi
 getConfiguredClient || exit 1
 
-
 while getopts 'ud:hv' flag; do
   case "${flag}" in
-    u) checkInternet || exit 1 # check if we have a valid internet connection if this isnt true the rest of the script will not work so stop here
-      update
-       exit 0 ;;
-    d) detail=true ;;
-    h) usage
-       exit 0 ;;
-    v) echo "Version $currentVersion"
-       exit 0 ;;
-    :) echo "Option -$OPTARG requires an argument." >&2
-       exit 1 ;;
-    *) exit 1 ;;
+  u)
+    checkInternet || exit 1 # check if we have a valid internet connection if this isnt true the rest of the script will not work so stop here
+    update
+    exit 0
+    ;;
+  d) detail=true ;;
+  h)
+    usage
+    exit 0
+    ;;
+  v)
+    echo "Version $currentVersion"
+    exit 0
+    ;;
+  :)
+    echo "Option -$OPTARG requires an argument." >&2
+    exit 1
+    ;;
+  *) exit 1 ;;
   esac
 done
 
@@ -203,7 +225,7 @@ elif [[ $1 == "update" ]]; then
 elif [[ $1 == "help" ]]; then
   usage
 else
-  checkInternet || exit 1 # check if we have a valid internet connection if this isnt true the rest of the script will not work so stop here
+  checkInternet || exit 1     # check if we have a valid internet connection if this isnt true the rest of the script will not work so stop here
   getMovieInfo "$@" || exit 1 ## exit if we return 1 (chances are movie was not found)
-  printMovieInfo ## print out the data
+  printMovieInfo              ## print out the data
 fi
diff --git a/bin/short b/bin/short
--- a/bin/short
+++ b/bin/short
@@ -6,9 +6,8 @@ configuredClient=""
 configuredPython=""
 
 ## This function determines which http get tool the system has installed and returns an error if there isnt one
-getConfiguredClient()
-{
-  if  command -v curl &>/dev/null; then
+getConfiguredClient() {
+  if command -v curl &>/dev/null; then
     configuredClient="curl"
   elif command -v wget &>/dev/null; then
     configuredClient="wget"
@@ -23,20 +22,17 @@ getConfiguredClient()
 }
 
 ## Allows to call the users configured client without if statements everywhere
-httpGet()
-{
+httpGet() {
   case "$configuredClient" in
-    curl)  curl -A curl -s "$@" ;;
-    wget)  wget -qO- "$@" ;;
-    httpie) http -b GET "$@" ;;
-    fetch) fetch -q "$@" ;;
+  curl) curl -A curl -s "$@" ;;
+  wget) wget -qO- "$@" ;;
+  httpie) http -b GET "$@" ;;
+  fetch) fetch -q "$@" ;;
   esac
 }
 
-
-getConfiguredPython()
-{
-  if  command -v python2 &>/dev/null; then
+getConfiguredPython() {
+  if command -v python2 &>/dev/null; then
     configuredPython="python2"
   elif command -v python &>/dev/null; then
     configuredPython="python"
@@ -46,31 +42,30 @@ getConfiguredPython()
   fi
 }
 
-if [[ $(uname) != "Darwin" ]];then
-  python()
-  {
+if [[ $(uname) != "Darwin" ]]; then
+  python() {
     case "$configuredPython" in
-      python2) python2 "$@" ;;
-      python)  python "$@" ;;
+    python2) python2 "$@" ;;
+    python) python "$@" ;;
     esac
   }
 fi
 
-
-checkInternet()
-{
-  httpGet github.com > /dev/null 2>&1 || { echo "Error: no active internet connection" >&2; return 1; } # query github with a get request
+checkInternet() {
+  httpGet github.com >/dev/null 2>&1 || {
+    echo "Error: no active internet connection" >&2
+    return 1
+  } # query github with a get request
 }
 
-update()
-{
+update() {
   # Author: Alexander Epstein https://github.com/alexanderepstein
   # Update utility version 2.2.0
   # To test the tool enter in the defualt values that are in the examples for each variable
-  repositoryName="Bash-Snippets" #Name of repostiory to be updated ex. Sandman-Lite
-  githubUserName="alexanderepstein" #username that hosts the repostiory ex. alexanderepstein
-  nameOfInstallFile="install.sh" # change this if the installer file has a different name be sure to include file extension if there is one
-  latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",'| head -1 | grep -Eo "[0-9.]+" ) #always grabs the tag without the v option
+  repositoryName="Bash-Snippets"                                                                                                                           #Name of repostiory to be updated ex. Sandman-Lite
+  githubUserName="alexanderepstein"                                                                                                                        #username that hosts the repostiory ex. alexanderepstein
+  nameOfInstallFile="install.sh"                                                                                                                           # change this if the installer file has a different name be sure to include file extension if there is one
+  latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",' | head -1 | grep -Eo "[0-9.]+") #always grabs the tag without the v option
 
   if [[ $currentVersion == "" || $repositoryName == "" || $githubUserName == "" || $nameOfInstallFile == "" ]]; then
     echo "Error: update utility has not been configured correctly." >&2
@@ -84,19 +79,37 @@ update()
       echo -n "Do you wish to update $repositoryName [Y/n]: "
       read -r answer
       if [[ "$answer" == [Yy] ]]; then
-        cd ~ || { echo 'Update Failed'; exit 1; }
-        if [[ -d  ~/$repositoryName ]]; then rm -r -f $repositoryName || { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
+        cd ~ || {
+          echo 'Update Failed'
+          exit 1
+        }
+        if [[ -d ~/$repositoryName ]]; then rm -r -f $repositoryName || {
+          echo "Permissions Error: try running the update as sudo"
+          exit 1
+        }; fi
         echo -n "Downloading latest version of: $repositoryName."
-        git clone -q "https://github.com/$githubUserName/$repositoryName" && touch .BSnippetsHiddenFile || { echo "Failure!"; exit 1; } &
-        while [ ! -f .BSnippetsHiddenFile ]; do { echo -n "."; sleep 2; };done
+        git clone -q "https://github.com/$githubUserName/$repositoryName" && touch .BSnippetsHiddenFile || {
+          echo "Failure!"
+          exit 1
+        } &
+        while [ ! -f .BSnippetsHiddenFile ]; do {
+          echo -n "."
+          sleep 2
+        }; done
         rm -f .BSnippetsHiddenFile
         echo "Success!"
-        cd $repositoryName || { echo 'Update Failed'; exit 1; }
-        git checkout "v$latestVersion" 2> /dev/null || git checkout "$latestVersion" 2> /dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
+        cd $repositoryName || {
+          echo 'Update Failed'
+          exit 1
+        }
+        git checkout "v$latestVersion" 2>/dev/null || git checkout "$latestVersion" 2>/dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
         chmod a+x install.sh #this might be necessary in your case but wasnt in mine.
         ./$nameOfInstallFile "update" || exit 1
         cd ..
-        rm -r -f $repositoryName || { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"; exit 1; }
+        rm -r -f $repositoryName || {
+          echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"
+          exit 1
+        }
       else
         exit 1
       fi
@@ -106,8 +119,7 @@ update()
   fi
 }
 
-usage()
-{
+usage() {
   cat <<EOF
 Short
 Description: Shorten urls and unmask shortended urls.
@@ -123,11 +135,10 @@ Example:
 EOF
 }
 
-expandURL()
-{
-  testURL=$( echo $1 | cut -c1-8 )
+expandURL() {
+  testURL=$(echo $1 | cut -c1-8)
   if [[ $testURL != "https://" ]]; then
-    testURL=$( echo $1 | cut -c1-7 )
+    testURL=$(echo $1 | cut -c1-7)
     if [[ $testURL != "http://" ]]; then
       url="http://$1"
     else
@@ -137,25 +148,23 @@ expandURL()
     url=$1
   fi
   response=$(httpGet http://ki.tc/short?url=$url)
-  errorCheck=$(echo $response | python -c "import sys, json; print json.load(sys.stdin)['/short']['message']" 2> /dev/null  )
+  errorCheck=$(echo $response | python -c "import sys, json; print json.load(sys.stdin)['/short']['message']" 2>/dev/null)
   if [[ $errorCheck == "Error in /short" ]]; then
-  echo "Error: 404 could not find the website"
-  return 1
-fi
-  returnedURL=$(echo $response | python -c "import sys, json; print json.load(sys.stdin)['/short']['destination']" 2>  /dev/null  )
+    echo "Error: 404 could not find the website"
+    return 1
+  fi
+  returnedURL=$(echo $response | python -c "import sys, json; print json.load(sys.stdin)['/short']['destination']" 2>/dev/null)
 
 }
 
-shortenURL()
-{
-newURL=$1
-if [[ $(echo $1 | grep -Eo "^[h]ttp[s]?://") == "" ]]; then newURL="http://"$1; fi
-response=$(curl -A curl -s -i -H "Content-Type: application/json" -X POST -d "{\"url\": \"$newURL\"}" http://ki.tc/ || exit 1)
-returnedURL=$(echo $response | grep -Eo "http://ki.tc/[0-9a-zA-Z]*" | tail -n 1)
+shortenURL() {
+  newURL=$1
+  if [[ $(echo $1 | grep -Eo "^[h]ttp[s]?://") == "" ]]; then newURL="http://"$1; fi
+  response=$(curl -A curl -s -i -H "Content-Type: application/json" -X POST -d "{\"url\": \"$newURL\"}" http://ki.tc/ || exit 1)
+  returnedURL=$(echo $response | grep -Eo "http://ki.tc/[0-9a-zA-Z]*" | tail -n 1)
 }
 
-printResults()
-{
+printResults() {
   cat <<EOF
 =====================================================================
 Short URL:    $inputURL
@@ -164,8 +173,7 @@ Expanded URL: $returnedURL
 EOF
 }
 
-printShortenedResults()
-{
+printShortenedResults() {
   cat <<EOF
 =====================================================================
 Original URL:  $newURL
@@ -177,37 +185,41 @@ EOF
 if [[ $(uname) != "Darwin" ]]; then getConfiguredPython || exit 1; fi
 getConfiguredClient || exit 1
 
-
 while getopts "e:s:uvh" opt; do
   case "$opt" in
-    \?) echo "Invalid option: -$OPTARG" >&2
-        exit 1
-        ;;
-    e)
-        expand="true"
-        inputURL=$OPTARG
-        ;;
-    s)
-        shorten="true"
-        inputURL=$OPTARG
-        ;;
-    h)  usage
-        exit 0
-        ;;
-    v)  echo "Version $currentVersion"
-        exit 0
-        ;;
-    u)  checkInternet || exit 1
-        update
-        exit 0
-        ;;
-    :)  echo "Option -$OPTARG requires an argument." >&2
-        exit 1
-        ;;
+  \?)
+    echo "Invalid option: -$OPTARG" >&2
+    exit 1
+    ;;
+  e)
+    expand="true"
+    inputURL=$OPTARG
+    ;;
+  s)
+    shorten="true"
+    inputURL=$OPTARG
+    ;;
+  h)
+    usage
+    exit 0
+    ;;
+  v)
+    echo "Version $currentVersion"
+    exit 0
+    ;;
+  u)
+    checkInternet || exit 1
+    update
+    exit 0
+    ;;
+  :)
+    echo "Option -$OPTARG requires an argument." >&2
+    exit 1
+    ;;
   esac
 done
 
-if  [[ $expand == "true" && $shorten == "true" ]];then
+if [[ $expand == "true" && $shorten == "true" ]]; then
   echo "Error: the -e and the -s options are mutually exclusive" >&2
   exit 1
 fi
@@ -226,12 +238,12 @@ elif [[ $# == "1" ]]; then
     usage
     exit 1
   fi
-elif [[ $expand == "true" ]];then
+elif [[ $expand == "true" ]]; then
   checkInternet || exit 1
   expandURL "$inputURL" || exit 1
   printResults
-elif [[ $shorten == "true" ]];then
-  if [[ $configuredClient != "curl" ]];then
+elif [[ $shorten == "true" ]]; then
+  if [[ $configuredClient != "curl" ]]; then
     echo "Error: to shorten URLS you must have curl installed"
   fi
   checkInternet || exit 1
diff --git a/bin/stocks b/bin/stocks
--- a/bin/stocks
+++ b/bin/stocks
@@ -7,9 +7,8 @@ configuredClient=""
 configuredPython=""
 
 ## This function determines which http get tool the system has installed and returns an error if there isnt one
-getConfiguredClient()
-{
-  if  command -v curl &>/dev/null; then
+getConfiguredClient() {
+  if command -v curl &>/dev/null; then
     configuredClient="curl"
   elif command -v wget &>/dev/null; then
     configuredClient="wget"
@@ -24,19 +23,17 @@ getConfiguredClient()
 }
 
 ## Allows to call the users configured client without if statements everywhere
-httpGet()
-{
+httpGet() {
   case "$configuredClient" in
-    curl)  curl -A curl -s "$@" ;;
-    wget)  wget -qO- "$@" ;;
-    httpie) http -b GET "$@" ;;
-    fetch) fetch -q "$@" ;;
+  curl) curl -A curl -s "$@" ;;
+  wget) wget -qO- "$@" ;;
+  httpie) http -b GET "$@" ;;
+  fetch) fetch -q "$@" ;;
   esac
 }
 
-getConfiguredPython()
-{
-  if  command -v python2 &>/dev/null; then
+getConfiguredPython() {
+  if command -v python2 &>/dev/null; then
     configuredPython="python2"
   elif command -v python &>/dev/null; then
     configuredPython="python"
@@ -47,27 +44,30 @@ getConfiguredPython()
 }
 
 if [[ $(uname) != "Darwin" ]]; then
-  python()
-  {
+  python() {
     case "$configuredPython" in
-      python2) python2 "$@" ;;
-      python)  python "$@" ;;
+    python2) python2 "$@" ;;
+    python) python "$@" ;;
     esac
   }
 fi
 
-checkInternet()
-{
-  httpGet github.com > /dev/null 2>&1 || { echo "Error: no active internet connection" >&2; return 1; } # query github with a get request
+checkInternet() {
+  httpGet github.com >/dev/null 2>&1 || {
+    echo "Error: no active internet connection" >&2
+    return 1
+  } # query github with a get request
 }
 
 ## This function grabs information about a stock and using python parses the
 ## JSON response to extrapolate the information for storage
-getStockInformation()
-{
-  stockInfo=$(httpGet  "https://api.iextrading.com/1.0/stock/$1/quote") > /dev/null #grab the JSON response
-  export PYTHONIOENCODING=utf8 #necessary for python in some cases
-  echo $stockInfo | python -c "import sys, json; print json.load(sys.stdin)['companyName']" > /dev/null 2>&1 || { echo "Not a valid stock symbol"; exit 1; } #checking if we get any information back from the server if not chances are it isnt a valid stock symbol
+getStockInformation() {
+  stockInfo=$(httpGet "https://api.iextrading.com/1.0/stock/$1/quote") >/dev/null #grab the JSON response
+  export PYTHONIOENCODING=utf8                                                    #necessary for python in some cases
+  echo $stockInfo | python -c "import sys, json; print json.load(sys.stdin)['companyName']" >/dev/null 2>&1 || {
+    echo "Not a valid stock symbol"
+    exit 1
+  } #checking if we get any information back from the server if not chances are it isnt a valid stock symbol
   # The rest of the code is just extrapolating the data with python from the JSON response
   exchangeName=$(echo $stockInfo | python -c "import sys, json; print json.load(sys.stdin)['primaryExchange']")
   latestPrice=$(echo $stockInfo | python -c "import sys, json; print json.load(sys.stdin)['latestPrice']")
@@ -84,20 +84,19 @@ getStockInformation()
 
 ## This function uses all the variables that are set by getStockInformation and
 ## prints them out to the user in a human readable format
-printStockInformation()
-{
+printStockInformation() {
   echo
   echo $symbol stock info
   echo "============================================="
   echo "| Exchange Name: $exchangeName"
   echo "| Latest Price: $latestPrice"
   if [[ $open != "--" ]]; then echo "| Open (Current Trading Day): $open"; fi ## sometime this is blank only print if value is present
-  if [[ $high != "--" ]]; then echo "| High (Week52): $high"; fi ## sometime this is blank only print if value is present
-  if [[ $low != "--" ]]; then echo "| Low (Week52): $low"; fi ## sometime this /is blank only print if value is present
+  if [[ $high != "--" ]]; then echo "| High (Week52): $high"; fi              ## sometime this is blank only print if value is present
+  if [[ $low != "--" ]]; then echo "| Low (Week52): $low"; fi                 ## sometime this /is blank only print if value is present
   echo "| Close (Previous Trading Day): $close"
   echo "| Price Change: $priceChange"
-  if [[ $priceChangePercentage != "%" ]];then echo "| Price Change Percentage: $priceChangePercentage"; fi ## sometime this is blank only print if value is present
-  if [[ $volume != "--" ]];then echo "| Volume (Current Trading Day): $volume"; fi ## sometime this is blank only print if value is present
+  if [[ $priceChangePercentage != "%" ]]; then echo "| Price Change Percentage: $priceChangePercentage"; fi ## sometime this is blank only print if value is present
+  if [[ $volume != "--" ]]; then echo "| Volume (Current Trading Day): $volume"; fi                         ## sometime this is blank only print if value is present
   echo "| Last Updated: $lastUpdated"
   echo "============================================="
   echo
@@ -106,23 +105,21 @@ printStockInformation()
 ## This function queries google to determine the stock ticker for a certain company
 ## this allows the usage of stocks to be extended where now you can enter stocks appple
 ## and it will determine the stock symbol for apple is AAPL and move on from there
-getTicker()
-{
+getTicker() {
   input=$(echo "$@" | tr " " +)
-  response=$(httpGet "http://d.yimg.com/autoc.finance.yahoo.com/autoc?query=$input&region=1&lang=en%22") > /dev/null
+  response=$(httpGet "http://d.yimg.com/autoc.finance.yahoo.com/autoc?query=$input&region=1&lang=en%22") >/dev/null
   symbol=$(echo $response | python -c "import sys, json; print json.load(sys.stdin)['ResultSet']['Result'][0]['symbol']") # using python to extrapolate the stock symbol
-  unset response #just unsets the entire response after using it since all I need is the stock ticker
+  unset response                                                                                                          #just unsets the entire response after using it since all I need is the stock ticker
 }
 
-update()
-{
+update() {
   # Author: Alexander Epstein https://github.com/alexanderepstein
   # Update utility version 2.2.0
   # To test the tool enter in the defualt values that are in the examples for each variable
-  repositoryName="Bash-Snippets" #Name of repostiory to be updated ex. Sandman-Lite
-  githubUserName="alexanderepstein" #username that hosts the repostiory ex. alexanderepstein
-  nameOfInstallFile="install.sh" # change this if the installer file has a different name be sure to include file extension if there is one
-  latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",'| head -1 | grep -Eo "[0-9.]+" ) #always grabs the tag without the v option
+  repositoryName="Bash-Snippets"                                                                                                                           #Name of repostiory to be updated ex. Sandman-Lite
+  githubUserName="alexanderepstein"                                                                                                                        #username that hosts the repostiory ex. alexanderepstein
+  nameOfInstallFile="install.sh"                                                                                                                           # change this if the installer file has a different name be sure to include file extension if there is one
+  latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",' | head -1 | grep -Eo "[0-9.]+") #always grabs the tag without the v option
 
   if [[ $currentVersion == "" || $repositoryName == "" || $githubUserName == "" || $nameOfInstallFile == "" ]]; then
     echo "Error: update utility has not been configured correctly." >&2
@@ -136,19 +133,37 @@ update()
       echo -n "Do you wish to update $repositoryName [Y/n]: "
       read -r answer
       if [[ "$answer" == [Yy] ]]; then
-        cd ~ || { echo 'Update Failed'; exit 1; }
-        if [[ -d  ~/$repositoryName ]]; then rm -r -f $repositoryName || { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
+        cd ~ || {
+          echo 'Update Failed'
+          exit 1
+        }
+        if [[ -d ~/$repositoryName ]]; then rm -r -f $repositoryName || {
+          echo "Permissions Error: try running the update as sudo"
+          exit 1
+        }; fi
         echo -n "Downloading latest version of: $repositoryName."
-        git clone -q "https://github.com/$githubUserName/$repositoryName" && touch .BSnippetsHiddenFile || { echo "Failure!"; exit 1; } &
-        while [ ! -f .BSnippetsHiddenFile ]; do { echo -n "."; sleep 2; };done
+        git clone -q "https://github.com/$githubUserName/$repositoryName" && touch .BSnippetsHiddenFile || {
+          echo "Failure!"
+          exit 1
+        } &
+        while [ ! -f .BSnippetsHiddenFile ]; do {
+          echo -n "."
+          sleep 2
+        }; done
         rm -f .BSnippetsHiddenFile
         echo "Success!"
-        cd $repositoryName || { echo 'Update Failed'; exit 1; }
-        git checkout "v$latestVersion" 2> /dev/null || git checkout "$latestVersion" 2> /dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
+        cd $repositoryName || {
+          echo 'Update Failed'
+          exit 1
+        }
+        git checkout "v$latestVersion" 2>/dev/null || git checkout "$latestVersion" 2>/dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
         chmod a+x install.sh #this might be necessary in your case but wasnt in mine.
         ./$nameOfInstallFile "update" || exit 1
         cd ..
-        rm -r -f $repositoryName || { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"; exit 1; }
+        rm -r -f $repositoryName || {
+          echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"
+          exit 1
+        }
       else
         exit 1
       fi
@@ -158,8 +173,7 @@ update()
   fi
 }
 
-usage()
-{
+usage() {
   cat <<EOF
 Stocks
 Description: Finds the latest information on a certain stock.
@@ -176,25 +190,29 @@ EOF
 if [[ $(uname) != "Darwin" ]]; then getConfiguredPython || exit 1; fi
 getConfiguredClient || exit 1
 
-
 while getopts "uvh" opt; do
   case "$opt" in
-    \?) echo "Invalid option: -$OPTARG" >&2
-        exit 1
-        ;;
-    h)  usage
-        exit 0
-        ;;
-    v)  echo "Version $currentVersion"
-        exit 0
-        ;;
-    u)  checkInternet || exit 1
-        update
-        exit 0
-        ;;
-    :)  echo "Option -$OPTARG requires an argument." >&2
-        exit 1
-        ;;
+  \?)
+    echo "Invalid option: -$OPTARG" >&2
+    exit 1
+    ;;
+  h)
+    usage
+    exit 0
+    ;;
+  v)
+    echo "Version $currentVersion"
+    exit 0
+    ;;
+  u)
+    checkInternet || exit 1
+    update
+    exit 0
+    ;;
+  :)
+    echo "Option -$OPTARG requires an argument." >&2
+    exit 1
+    ;;
   esac
 done
 
@@ -210,8 +228,8 @@ elif [[ $# == "0" ]]; then
   exit 0
 else
   checkInternet || exit 1
-  getTicker "$@" # the company name might have spaces so passing in all args allows for this
+  getTicker "$@"              # the company name might have spaces so passing in all args allows for this
   getStockInformation $symbol # based on the stock symbol exrapolated by the getTicker function get information on the stock
-  printStockInformation  # print this information out to the user in a human readable format
+  printStockInformation       # print this information out to the user in a human readable format
   exit 0
 fi
